### ISSUE TITLE
Feature Request: Clipboard Import using decimal

### ISSUE THREAD

**Issue by Dpons039** [peterhaneve/evemon#101]
Hello,

I'm using Pyfa to check fittings on ships but from time to time I come accross fittings that are lacking skills, on those cases I just go ahead to copy the missing skills, this is the output from Pyfa:

> Caldari Dreadnought 1
> Capital Shield Operation 1
> Capital Ships 3
> Tactical Weapon Reconfiguration 5
> Torpedo Specialization 1
> Torpedoes 5

I then attempt to "Clipboard Import" those values into EVEMon Skill Planner but it seems to only accept Roman Numbers... So I usually rename the values to Roman and then "Clipboard Import" again.

> Caldari Dreadnought I
> Capital Shield Operation I
> Capital Ships III
> Tactical Weapon Reconfiguration V
> Torpedo Specialization I
> Torpedoes V

I'm unsure if this is in fact a Feature for EVEMon or Pyfa, hope you through some light here :)

Thank you very much for keeping EVEMon alive, it's the best :D

**Comment by peterhaneve** [comment]
The clipboard import is intended for the EVE in game skill copy/paste feature. Does this feature also accept Roman numerals?

**Comment by Dpons039** [comment]
Hello!

I was checking that and it does look like EVE allows both Decimal and Roman numbers:
![image](https://user-images.githubusercontent.com/3227283/47574460-f0262980-d93f-11e8-8a80-cabfdca86646.png)

But If I have the skills with decimal numbers at the clipboard and I try to add them to EVEMon it returns an error:
![image](https://user-images.githubusercontent.com/3227283/47574546-1946ba00-d940-11e8-893f-f4f3ebf90b2d.png)

It looks like EVEMon does not like the decimal numbers

**Comment by Dpons039** [comment]
Thank you very much Peter, that was quick!!!

Fly safe
