### ISSUE TITLE
Incorrectly displaying training times and sp/h

### ISSUE THREAD

**Issue by ApoLamperouge** [peterhaneve/evemon#102]
https://i.imgur.com/LM3etdl.png

attributes set for perception/willpower but showing 1125 sp/h and 93d 15h to train to level 5

**Comment by BoraVyvorant** [comment]
Just updated. Same behaviour. Evemon has misdetected my account as Alpha, so training times seem to be doubled.

**Comment by peterhaneve** [comment]
Something is different about your accounts versus the test scenario. Have you logged in recently? How many SP does your character have, and what skill is it currently training?

**Comment by ToastyGPUs** [comment]
I'm seeing this as well on an Omega character with 250mil SP training Jump Drive Calibration V. EVEMon doesn't seem to be able to tell I'm an Omega.

**Comment by BoraVyvorant** [comment]
110M SP, Capital Ships IV, has recently logged in.

**Comment by ApoLamperouge** [comment]
OK so it seems that that bug has resolved itself for me, but now every time
my computer starts up, Evemon crashes. I have now turned off "run at
startup".
One thing I have noticed lately is assets are not being displayed, and if
you do a search, Evemon will crash.

Anyway thought you might like to know.
