### ISSUE TITLE
Error if started minimized on windows start up

### ISSUE THREAD

**Issue by Krisscut** [peterhaneve/evemon#103]
Hi,

Since the last update i have this error when evemon is started minimized when i log in on windows:

> EVEMon Version: 4.0.9.4875
> .NET Runtime Version: 4.0.30319.42000
> Operating System: Microsoft Windows NT 10.0.17134.0
> Executable Path: "F:\Program Files (x86)\EVEMon\EVEMon.exe" -startMinimized
> System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.TypeInitializationException: Une exception a été levée par l'initialiseur de type pour 'EVEMon.Common.Settings'. ---> System.Reflection.ReflectionTypeLoadException: Impossible de charger un ou plusieurs des types requis. Extrayez la propriété LoaderExceptions pour plus d'informations.
>    à System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
>    à System.Reflection.Assembly.GetTypes()
>    à EVEMon.Common.MarketPricer.ItemPricer.get_Providers()
>    à EVEMon.Common.SettingsObjects.MarketPricerSettings..ctor()
>    à EVEMon.Common.Settings..cctor()
>    --- Fin de la trace de la pile d'exception interne ---
>    à EVEMon.Common.Settings.Initialize()
>    à EVEMon.Program.<StartupAsync>d__4.MoveNext()
>    --- Fin de la trace de la pile d'exception interne ---
>    à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    à EVEMon.Program.Main()
> ---> (Exception interne #0) System.TypeInitializationException: Une exception a été levée par l'initialiseur de type pour 'EVEMon.Common.Settings'. ---> System.Reflection.ReflectionTypeLoadException: Impossible de charger un ou plusieurs des types requis. Extrayez la propriété LoaderExceptions pour plus d'informations.
>    à System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
>    à System.Reflection.Assembly.GetTypes()
>    à EVEMon.Common.MarketPricer.ItemPricer.get_Providers()
>    à EVEMon.Common.SettingsObjects.MarketPricerSettings..ctor()
>    à EVEMon.Common.Settings..cctor()
>    --- Fin de la trace de la pile d'exception interne ---
>    à EVEMon.Common.Settings.Initialize()
>    à EVEMon.Program.<StartupAsync>d__4.MoveNext()<---
> 
> 
> System.TypeInitializationException: Une exception a été levée par l'initialiseur de type pour 'EVEMon.Common.Settings'. ---> System.Reflection.ReflectionTypeLoadException: Impossible de charger un ou plusieurs des types requis. Extrayez la propriété LoaderExceptions pour plus d'informations.
>    à System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
>    à System.Reflection.Assembly.GetTypes()
>    à EVEMon.Common.MarketPricer.ItemPricer.get_Providers()
>    à EVEMon.Common.SettingsObjects.MarketPricerSettings..ctor()
>    à EVEMon.Common.Settings..cctor()
>    --- Fin de la trace de la pile d'exception interne ---
>    à EVEMon.Common.Settings.Initialize()
>    à EVEMon.Program.<StartupAsync>d__4.MoveNext()
> 
> System.Reflection.ReflectionTypeLoadException: Impossible de charger un ou plusieurs des types requis. Extrayez la propriété LoaderExceptions pour plus d'informations.
>    à System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
>    à System.Reflection.Assembly.GetTypes()
>    à EVEMon.Common.MarketPricer.ItemPricer.get_Providers()
>    à EVEMon.Common.SettingsObjects.MarketPricerSettings..ctor()
>    à EVEMon.Common.Settings..cctor()
> 
> 
> Datafile report:
>   eve-blueprints-en-US.xml.gzip (201KiB - 219eb76e35e9c1df32d2b7f21268582c)
>   eve-certificates-en-US.xml.gzip (45KiB - 540000f7c111354769a54fa31e57d411)
>   eve-geography-en-US.xml.gzip (1010KiB - 062c656d9913c91533ec4bca655b4825)
>   eve-items-en-US.xml.gzip (2450KiB - e38416ecdacb373def52430f21396335)
>   eve-masteries-en-US.xml.gzip (21KiB - 3668b50996fc40a0c0853fec427b5712)
>   eve-properties-en-US.xml.gzip (61KiB - b67334c7fde7b2f1cbfacfb7674cd0ce)
>   eve-reprocessing-en-US.xml.gzip (110KiB - a04bf832a8e9dba50d063f3e9b2cfda4)
>   eve-skills-en-US.xml.gzip (24KiB - 8ae1b941516ea580cf4724d9ea3b6999)
> 
> 
> Diagnostic Log:
> 0d 0h 00m 00s > Starting up
> 0d 0h 00m 00s > EveMonClient.Initialize - begin
> 0d 0h 00m 00s > Program.StartupAsync - done
> 

Then i get this error message:
https://i.imgur.com/mdVOCUP.png

If i click on "Close Evemon", then start it up again there are no errors.

**Comment by peterhaneve** [comment]
This is a bug in one of EVEMon's dependencies. I ran into it as well after updating Visual Studio to 2017 (in the designer no less) and fixed it by updating all of the dependencies in the project.

**Comment by Krisscut** [comment]
Thanks for the quick reaction & fix, awesome work ! 👍
