### ISSUE TITLE
Error when trying to update

### ISSUE THREAD

**Issue by Krisscut** [peterhaneve/evemon#104]
Hi again,

I have this error when trying to update to the newest version that just popped up:
https://i.imgur.com/AIVh1OT.png

I don't know where the logs are stored, so that maybe i can provide those to you to help debugging ?

**Comment by peterhaneve** [comment]
This looks like a mismatch in the installer MD5 and patch file due to GIT's caching. Try again in an hour or so, that should be long enough for all caches to flush.
