### ISSUE TITLE
Some items have strange names

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#113]
Hi

Small issue: The **Standard 'Radiance' Cerebral Accelerator** shows up as S10 on the Waller Tab. I've also seen other similar values.

**Comment by peterhaneve** [comment]
This is due to the EVEMon SDE being out of date. Once CCP releases the Onslaught SDE, this particular instance will be fixed.

**Comment by wvdvegt** [comment]
Is downloading missing stuff from ESI not an option?
