### ISSUE TITLE
Blueprints missing from industry

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#114]
Hi,

Small issue I think: The **Standup Cap Battery I Blueprint** does not show up under industry. The count is adjusted (incorrectly for it) as well. So it looks like i have 1 unused job where I have the max running.

I've seen this in the past as well with new items like the **Assault Damage Control**.

**Comment by wbSD** [comment]
It looks like the xml generator code for blueprints was removed back in the original (pre-PeterHan) attempt at converting to ESI
https://github.com/peterhaneve/evemon/commit/f9e5dfb1f38c2cc92c8ea0526135a73e025a7b4b#diff-67a0b4787c1e9dc5ba8a6552e52b58e8L36

**Comment by wbSD** [comment]
I wrote a query that yields the same data that used to be in invBlueprintTypes in the same format that the xml generator expects it
https://gist.github.com/wbSD/af23d62d682fbb0b1d33f15a2efae7d2

Still can't generate the blueprints file, need to do something similar for ramTypeRequirements
Will update if/when I have any progress

**Comment by peterhaneve** [comment]
`invBlueprintTypes` also had a `parentBlueprintTypeID` field when it existed, but it appears that the XML generator never used this field.

**Comment by wvdvegt** [comment]
Is retrieving the missing data from ESI not a (better) option? It would only have to work between updates containing updated static data.

In my private EveMonitor application I even download all data from ESI (so no static all all).

**Comment by wbSD** [comment]
I agree that it would be a better long term solution to update the data structure of evemon to match what it actually is, but it's a bit of a bigger task than making the new blueprint data structure backwards compatible with 2 simple queries against the sqlite database that evemon already uses to generate the static data.

I was looking at the data available from ESI, but there were certain things that I wasn't able to identify.
For example which types of industry activity a blueprint allows for, what the required skills and materials are, the probability and the output

**Comment by wvdvegt** [comment]
ESI is still not a full replacement.

The only portability i could find is in /characters/{character_id}/industry/jobs/ (so incorporates the pilot's skills as well). I would also not be surprised if some data is in the dogma endpoints.

But you are probably looking for the data to be shown in the blueprint browser. I just tried the swagger interface for a mammoth bpo (type id 987) and got a whole load of dogma attributes in return. But all are on size/mass/volume etc.

Probability is fixed to the size of the BPO (size as in ship type), then adjusted for the location where being invented as well. Just a formula if i remember it correctly.

See [invention_chance](http://games.chruker.dk/eve_online/invention_chance.php?skill_datacore_1=3&skill_datacore_2=3&base_chance=30&skill_encryption=4&decryptor=modifier10&precalculated_chance=absolute).

Maybe ask in Slack (and hope CCP has an answer there)
