### ISSUE TITLE
EveMon crash when try to search an item in Display Assets

### ISSUE THREAD

**Issue by florica76** [peterhaneve/evemon#125]
EVEMon Version: 4.0.9.4882
.NET Runtime Version: 4.0.30319.42000
Operating System: Microsoft Windows NT 10.0.17763.0
Executable Path: "C:\Games\EveMon\EVEMon.exe" 
System.NullReferenceException: Object reference not set to an instance of an object.
   at EVEMon.CharacterMonitoring.CharacterAssetsList.IsTextMatching(Asset x, String text)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EVEMon.CharacterMonitoring.CharacterAssetsList.<UpdateContentAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EVEMon.CharacterMonitoring.CharacterAssetsList.<EveMonClient_ItemPricesUpdated>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

Datafile report:
  eve-blueprints-en-US.xml.gzip (222KiB - 37d2cddd9aad3d7fe7183d4de445e945)
  eve-certificates-en-US.xml.gzip (45KiB - 540000f7c111354769a54fa31e57d411)
  eve-geography-en-US.xml.gzip (1010KiB - 062c656d9913c91533ec4bca655b4825)
  eve-items-en-US.xml.gzip (2477KiB - 92e7ab9a0f823d71df7120e473dccbce)
  eve-masteries-en-US.xml.gzip (21KiB - 3668b50996fc40a0c0853fec427b5712)
  eve-properties-en-US.xml.gzip (62KiB - 5673fb8b543c187a90d8ed1870e29345)
  eve-reprocessing-en-US.xml.gzip (111KiB - 9c19069159e492f8486a58efcbb18bc8)
  eve-skills-en-US.xml.gzip (24KiB - bed294b41359401aeb808af2a59f3df4)

Diagnostic Log:
0d 0h 00m 00s > Starting up
0d 0h 00m 00s > EveMonClient.Initialize - begin
0d 0h 00m 00s > Program.StartupAsync - done
0d 0h 00m 00s > Settings.TryDeserializeFromFile - begin
0d 0h 00m 01s > Settings.TryDeserializeFromFile - done
0d 0h 00m 01s > Settings.Import - begin
0d 0h 00m 01s > EveMonClient.OnSchedulerChanged
0d 0h 00m 01s > Settings.Import - done
0d 0h 00m 01s > EveMonClient.OnSettingsChanged
0d 0h 00m 01s > Main loop - start
0d 0h 00m 01s > MainWindow.OnLoad
0d 0h 00m 01s > TimeCheck.ScheduleCheck - in 00:00:01
0d 0h 00m 01s > UpdateManager.ScheduleCheck - in 00:00:10
0d 0h 00m 01s > Main window - loaded
0d 0h 00m 01s > Datafiles.Load - begin
0d 0h 00m 02s > TimeCheck.BeginCheckAsync
0d 0h 00m 02s > TimeCheck.OnCheckCompleted - Synchronised
0d 0h 00m 02s > TimeCheck.ScheduleCheck - in 1.00:00:00
0d 0h 00m 02s > EveMonClient.OnServerStatusUpdated
0d 0h 00m 06s > Datafiles.Load - done
0d 0h 00m 06s > Settings.ImportData - begin
0d 0h 00m 06s > EveMonClient.OnCharacterImplantSetCollectionChanged - DonFlorica Tissant
0d 0h 00m 06s > EveMonClient.OnCharacterSkillQueueUpdated - DonFlorica Tissant
0d 0h 00m 07s > EveMonClient.OnCharacterUpdated - DonFlorica Tissant
0d 0h 00m 07s > EveMonClient.OnCharacterImplantSetCollectionChanged - Corcod3L
0d 0h 00m 07s > EveMonClient.OnCharacterSkillQueueUpdated - Corcod3L
0d 0h 00m 07s > EveMonClient.OnCharacterUpdated - Corcod3L
0d 0h 00m 07s > EveMonClient.OnCharacterImplantSetCollectionChanged - Mirabela Tissant
0d 0h 00m 07s > EveMonClient.OnCharacterSkillQueueUpdated - Mirabela Tissant
0d 0h 00m 07s > EveMonClient.OnCharacterUpdated - Mirabela Tissant
0d 0h 00m 07s > EveMonClient.OnCharacterImplantSetCollectionChanged - Gagicara
0d 0h 00m 07s > EveMonClient.OnCharacterSkillQueueUpdated - Gagicara
0d 0h 00m 07s > EveMonClient.OnCharacterUpdated - Gagicara
0d 0h 00m 07s > EveMonClient.OnCharacterCollectionChanged
0d 0h 00m 07s > EveMonClient.OnESIKeyCollectionChanged
0d 0h 00m 07s > EveMonClient.OnEveIDToNameUpdated
0d 0h 00m 07s > EveMonClient.OnCharacterInfoUpdated - DonFlorica Tissant
0d 0h 00m 07s > EveMonClient.OnCharacterInfoUpdated - Corcod3L
0d 0h 00m 07s > EveMonClient.OnCharacterInfoUpdated - Mirabela Tissant
0d 0h 00m 07s > EveMonClient.OnCharacterInfoUpdated - Gagicara
0d 0h 00m 07s > EveMonClient.OnCharacterPlanCollectionChanged - DonFlorica Tissant
0d 0h 00m 07s > EveMonClient.OnCharacterPlanCollectionChanged - Corcod3L
0d 0h 00m 07s > EveMonClient.OnCharacterPlanCollectionChanged - Mirabela Tissant
0d 0h 00m 07s > EveMonClient.OnCharacterPlanCollectionChanged - Gagicara
0d 0h 00m 07s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 08s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 08s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 09s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 09s > Settings.ImportData - done
0d 0h 00m 09s > EveMonClient.OnSettingsChanged
0d 0h 00m 10s > EveMonClient.OnCharacterUpdated - DonFlorica Tissant
0d 0h 00m 10s > EveMonClient.OnCharacterListUpdated - 131720565776278352 (DonFlorica Tissant)
0d 0h 00m 10s > EveMonClient.OnESIKeyCollectionChanged
0d 0h 00m 10s > EveMonClient.OnESIKeyInfoUpdated - 131720565776278352 (DonFlorica Tissant)
0d 0h 00m 10s > EveMonClient.OnCharacterUpdated - Gagicara
0d 0h 00m 10s > EveMonClient.OnCharacterListUpdated - 131783252389573564 (Gagicara)
0d 0h 00m 10s > EveMonClient.OnESIKeyCollectionChanged
0d 0h 00m 10s > EveMonClient.OnESIKeyInfoUpdated - 131783252389573564 (Gagicara)
0d 0h 00m 10s > EveMonClient.OnCharacterUpdated - Mirabela Tissant
0d 0h 00m 10s > EveMonClient.OnCharacterListUpdated - 131775193908531776 (Mirabela Tissant)
0d 0h 00m 10s > EveMonClient.OnESIKeyCollectionChanged
0d 0h 00m 10s > EveMonClient.OnESIKeyInfoUpdated - 131775193908531776 (Mirabela Tissant)
0d 0h 00m 10s > EveMonClient.OnCharacterUpdated - Corcod3L
0d 0h 00m 10s > EveMonClient.OnCharacterListUpdated - 131775193314170258 (Corcod3L)
0d 0h 00m 10s > EveMonClient.OnESIKeyCollectionChanged
0d 0h 00m 10s > EveMonClient.OnESIKeyInfoUpdated - 131775193314170258 (Corcod3L)
0d 0h 00m 11s > EveMonClient.OnCharacterIndustryJobsUpdated - DonFlorica Tissant
0d 0h 00m 11s > EveMonClient.OnIndustryJobsUpdated - DonFlorica Tissant
0d 0h 00m 11s > EveMonClient.OnCharacterResearchPointsUpdated - DonFlorica Tissant
0d 0h 00m 11s > EveMonClient.OnCharacterIndustryJobsUpdated - Gagicara
0d 0h 00m 11s > EveMonClient.OnIndustryJobsUpdated - Gagicara
0d 0h 00m 11s > EveMonClient.OnCharacterResearchPointsUpdated - Mirabela Tissant
0d 0h 00m 11s > EveMonClient.OnCharacterResearchPointsUpdated - Gagicara
0d 0h 00m 11s > EveMonClient.OnCharacterIndustryJobsUpdated - Mirabela Tissant
0d 0h 00m 11s > EveMonClient.OnIndustryJobsUpdated - Mirabela Tissant
0d 0h 00m 11s > EveMonClient.OnCharacterMarketOrdersUpdated - Mirabela Tissant
0d 0h 00m 11s > EveMonClient.OnMarketOrdersUpdated - Mirabela Tissant
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryColoniesUpdated - Mirabela Tissant
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryColoniesUpdated - Gagicara
0d 0h 00m 11s > EveMonClient.OnCharacterMarketOrdersUpdated - Corcod3L
0d 0h 00m 11s > EveMonClient.OnMarketOrdersUpdated - Corcod3L
0d 0h 00m 11s > EveMonClient.OnCharacterResearchPointsUpdated - Corcod3L
0d 0h 00m 11s > EveMonClient.OnCharacterIndustryJobsUpdated - Corcod3L
0d 0h 00m 11s > EveMonClient.OnIndustryJobsUpdated - Corcod3L
0d 0h 00m 11s > EveMonClient.OnCharacterEVENotificationsUpdated - Gagicara
0d 0h 00m 11s > EveMonClient.OnCharacterEVENotificationsUpdated - Mirabela Tissant
0d 0h 00m 11s > EveMonClient.OnCharacterEVENotificationsUpdated - Corcod3L
0d 0h 00m 11s > EveMonClient.OnCharacterEVENotificationsUpdated - DonFlorica Tissant
0d 0h 00m 11s > CitadelStationProvider.FetchIDs - ESI lookup for 1023736622218 using 131720565776278352 (DonFlorica Tissant)
0d 0h 00m 11s > EveMonClient.OnCharacterMarketOrdersUpdated - DonFlorica Tissant
0d 0h 00m 11s > EveMonClient.OnMarketOrdersUpdated - DonFlorica Tissant
0d 0h 00m 11s > EveMonClient.OnCharacterMarketOrdersUpdated - Gagicara
0d 0h 00m 11s > EveMonClient.OnMarketOrdersUpdated - Gagicara
0d 0h 00m 11s > EveMonClient.OnCharacterEVEMailMessagesUpdated - Gagicara
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryColoniesUpdated - Corcod3L
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryColoniesUpdated - DonFlorica Tissant
0d 0h 00m 11s > EveMonClient.OnCharacterEVEMailMessagesUpdated - Mirabela Tissant
0d 0h 00m 11s > EveMonClient.OnCharacterEVEMailMessagesUpdated - DonFlorica Tissant
0d 0h 00m 11s > EveMonClient.OnCharacterEVEMailMessagesUpdated - Corcod3L
0d 0h 00m 11s > CitadelStationProvider.FetchIDs - ESI lookup for 1026178517552 using 131720565776278352 (DonFlorica Tissant)
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryLayoutUpdated - DonFlorica Tissant
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryLayoutUpdated - DonFlorica Tissant
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryLayoutUpdated - DonFlorica Tissant
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryLayoutUpdated - DonFlorica Tissant
0d 0h 00m 11s > EveMonClient.OnCharacterPlanetaryLayoutUpdated - DonFlorica Tissant
0d 0h 00m 11s > EveMonClient.OnConquerableStationListUpdated
0d 0h 00m 11s > EveMonClient.OnEveIDToNameUpdated
0d 0h 00m 12s > UpdateManager.OnCheckCompleted
0d 0h 00m 12s > UpdateManager.ScheduleCheck - in 12:00:00
0d 0h 00m 23s > CitadelStationProvider.FetchIDs - ESI lookup for 1022887360034 using 131720565776278352 (DonFlorica Tissant)
0d 0h 00m 23s > CitadelStationProvider.FetchIDs - ESI lookup for 1028737718454 using 131720565776278352 (DonFlorica Tissant)
0d 0h 00m 23s > EveMonClient.OnConquerableStationListUpdated
0d 0h 00m 33s > EveMonClient.OnEveIDToNameUpdated
0d 0h 00m 36s > EveMonClient.OnNotificationRefTypesUpdated
0d 0h 03m 40s > EveMonClient.OnCorporationMarketOrdersUpdated - Strategic Lions Inc.
0d 0h 03m 40s > EveMonClient.OnMarketOrdersUpdated - Gagicara
0d 0h 03m 40s > EveMonClient.OnCorporationMarketOrdersUpdated - Influenza Inc.
0d 0h 03m 40s > EveMonClient.OnMarketOrdersUpdated - DonFlorica Tissant
0d 0h 03m 50s > EveMonClient.OnCharacterAssetsUpdated - Mirabela Tissant
0d 0h 03m 50s > EveMonClient.OnCharacterAssetsUpdated - Corcod3L
0d 0h 03m 51s > EveFlag.Import - begin
0d 0h 03m 51s > EveFlag.OnDownloaded - done
0d 0h 03m 51s > EveMonClient.OnEveFlagsUpdated
0d 0h 03m 53s > EveMonClient.OnCharacterWalletJournalUpdated - Gagicara
0d 0h 03m 53s > EveMonClient.OnCharacterWalletJournalUpdated - Mirabela Tissant
0d 0h 03m 53s > EveMonClient.OnCharacterAssetsUpdated - Gagicara
0d 0h 03m 54s > EveMonClient.OnCharacterWalletJournalUpdated - Corcod3L
0d 0h 03m 56s > CitadelStationProvider.FetchIDs - ESI lookup for 1029249280575 using 131720565776278352 (DonFlorica Tissant)
0d 0h 03m 56s > EveMonClient.OnCharacterAssetsUpdated - DonFlorica Tissant
0d 0h 03m 56s > CitadelStationProvider.FetchIDs - ESI lookup for 1020993443196 using 131720565776278352 (DonFlorica Tissant)
0d 0h 03m 56s > CitadelStationProvider.FetchIDs - ESI lookup for 1022318111012 using 131720565776278352 (DonFlorica Tissant)
0d 0h 03m 56s > EveMonClient.OnCharacterWalletTransactionsUpdated - Mirabela Tissant
0d 0h 03m 56s > EveMonClient.OnCharacterWalletTransactionsUpdated - Corcod3L
0d 0h 03m 56s > EveMonClient.OnCharacterWalletTransactionsUpdated - DonFlorica Tissant
0d 0h 03m 56s > EveMonClient.OnCharacterWalletTransactionsUpdated - Gagicara
0d 0h 03m 57s > CitadelStationProvider.FetchIDs - ESI lookup for 1022610243246 using 131720565776278352 (DonFlorica Tissant)
0d 0h 03m 57s > CitadelStationProvider.FetchIDs - ESI lookup for 1023470732511 using 131720565776278352 (DonFlorica Tissant)
0d 0h 03m 57s > EveMonClient.OnEveIDToNameUpdated
0d 0h 03m 57s > CitadelStationProvider.OnQueryStationUpdated - Citadel Hunt failed for 1020993443196
0d 0h 03m 57s > CitadelStationProvider.FetchIDs - ESI lookup for 1025012761433 using 131720565776278352 (DonFlorica Tissant)
0d 0h 03m 57s > CitadelStationProvider.FetchIDs - ESI lookup for 1026115810010 using 131720565776278352 (DonFlorica Tissant)
0d 0h 03m 57s > CitadelStationProvider.FetchIDs - ESI lookup for 1026960906556 using 131720565776278352 (DonFlorica Tissant)
0d 0h 03m 57s > CitadelStationProvider.OnQueryStationUpdated - Citadel Hunt failed for 1023470732511
0d 0h 03m 57s > CitadelStationProvider.FetchIDs - ESI lookup for 1027284517923 using 131720565776278352 (DonFlorica Tissant)
0d 0h 03m 58s > CitadelStationProvider.FetchIDs - ESI lookup for 1027847404873 using 131720565776278352 (DonFlorica Tissant)
0d 0h 03m 58s > CitadelStationProvider.FetchIDs - ESI lookup for 1028009725347 using 131720565776278352 (DonFlorica Tissant)
0d 0h 03m 58s > CitadelStationProvider.FetchIDs - ESI lookup for 1028858195912 using 131775193908531776 (Mirabela Tissant)
0d 0h 03m 58s > EveMonClient.OnConquerableStationListUpdated
0d 0h 03m 58s > EveMonClient.OnConquerableStationListUpdated
0d 0h 03m 58s > EveMonClient.OnConquerableStationListUpdated
0d 0h 07m 29s > EveMonClient.OnNotificationSent - Error querying industry jobs for Influenza Inc..
0d 0h 07m 29s > EveMonClient.OnNotificationSent - Error querying industry jobs for Influenza Inc..
0d 0h 07m 49s > EveMonClient.OnCharacterKillLogUpdated - Mirabela Tissant
0d 0h 07m 49s > EveMonClient.OnCharacterKillLogUpdated - DonFlorica Tissant
0d 0h 07m 49s > EveMonClient.OnCharacterKillLogUpdated - Gagicara
0d 0h 07m 49s > EveMonClient.OnCharacterContactsUpdated - Gagicara
0d 0h 07m 49s > EveMonClient.OnCharacterContactsUpdated - Corcod3L
0d 0h 07m 49s > EveMonClient.OnCharacterContactsUpdated - DonFlorica Tissant
0d 0h 07m 49s > EveMonClient.OnNotificationSent - Error obtaining kill mail bab8d8a272beea76ba0e23271e3b3dc7308fd992 from the server.
0d 0h 07m 50s > EveMonClient.OnCharacterKillLogUpdated - DonFlorica Tissant
0d 0h 07m 50s > EveMonClient.OnNotificationInvalidated
0d 0h 07m 50s > EveMonClient.OnCharacterSkillQueueUpdated - Gagicara
0d 0h 07m 50s > EveMonClient.OnNotificationSent - 3 skills completed.
0d 0h 07m 50s > EveMonClient.OnCharacterQueuedSkillsCompleted - Mirabela Tissant
0d 0h 07m 50s > EveMonClient.OnCharacterSkillQueueUpdated - Mirabela Tissant
0d 0h 07m 50s > EveMonClient.OnCharacterSkillQueueUpdated - Corcod3L
0d 0h 07m 50s > EveMonClient.OnCharacterKillLogUpdated - Corcod3L
0d 0h 07m 50s > EveMonClient.OnCharacterContactsUpdated - Mirabela Tissant
0d 0h 07m 50s > EveMonClient.OnCharacterSkillQueueUpdated - DonFlorica Tissant
0d 0h 07m 50s > EveMonClient.OnEveIDToNameUpdated
0d 0h 07m 50s > EveMonClient.OnCharacterKillLogUpdated - Corcod3L
0d 0h 07m 51s > EveMonClient.OnEveIDToNameUpdated
0d 0h 07m 54s > EveMonClient.OnCharacterContractsUpdated - Gagicara
0d 0h 07m 54s > EveMonClient.OnContractsUpdated - Gagicara
0d 0h 07m 54s > EveMonClient.OnCharacterContractsUpdated - Mirabela Tissant
0d 0h 07m 54s > EveMonClient.OnContractsUpdated - Mirabela Tissant
0d 0h 07m 55s > EveMonClient.OnCharacterContractsUpdated - Corcod3L
0d 0h 07m 55s > EveMonClient.OnContractsUpdated - Corcod3L
0d 0h 07m 56s > CitadelStationProvider.FetchIDs - ESI lookup for 1026130391422 using 131720565776278352 (DonFlorica Tissant)
0d 0h 07m 56s > EveMonClient.OnCharacterContractsUpdated - DonFlorica Tissant
0d 0h 07m 56s > EveMonClient.OnContractsUpdated - DonFlorica Tissant
0d 0h 07m 56s > CitadelStationProvider.FetchIDs - ESI lookup for 1024850025591 using 131720565776278352 (DonFlorica Tissant)
0d 0h 07m 56s > EveMonClient.OnConquerableStationListUpdated
0d 0h 07m 56s > EveMonClient.OnEveIDToNameUpdated
0d 0h 08m 03s > EveMonClient.OnCorporationIndustryJobsUpdated - DonFlorica Tissant
0d 0h 08m 03s > EveMonClient.OnIndustryJobsUpdated - DonFlorica Tissant
0d 0h 08m 03s > EveMonClient.OnCorporationIndustryJobsUpdated - Gagicara
0d 0h 08m 03s > EveMonClient.OnIndustryJobsUpdated - Gagicara
0d 0h 08m 04s > CitadelStationProvider.OnQueryStationUpdated - Citadel Hunt failed for 1024701925488
0d 0h 08m 04s > EveMonClient.OnConquerableStationListUpdated
0d 0h 08m 04s > EveMonClient.OnCorporationIndustryJobsCompleted - Influenza Inc.
0d 0h 08m 04s > EveMonClient.OnCorporationIndustryJobsCompleted - Strategic Lions Inc.
0d 0h 08m 06s > EveMonClient.OnCorporationContractsUpdated - Strategic Lions Inc.
0d 0h 08m 06s > EveMonClient.OnContractsUpdated - Gagicara
0d 0h 08m 11s > CitadelStationProvider.FetchIDs - ESI lookup for 1023809940359 using 131720565776278352 (DonFlorica Tissant)
0d 0h 08m 11s > EveMonClient.OnCorporationContractsUpdated - Influenza Inc.
0d 0h 08m 11s > EveMonClient.OnContractsUpdated - DonFlorica Tissant
0d 0h 08m 11s > CitadelStationProvider.FetchIDs - ESI lookup for 1022036649791 using 131720565776278352 (DonFlorica Tissant)
0d 0h 08m 12s > EveMonClient.OnCorporationContractsUpdated - Influenza Inc.
0d 0h 08m 12s > EveMonClient.OnContractsUpdated - Mirabela Tissant
0d 0h 08m 12s > EveMonClient.OnEveIDToNameUpdated
0d 0h 08m 12s > CitadelStationProvider.FetchIDs - ESI lookup for 1022036649791 using 131775193908531776 (Mirabela Tissant)
0d 0h 08m 12s > EveMonClient.OnCorporationContractsUpdated - Influenza Inc.
0d 0h 08m 12s > EveMonClient.OnContractsUpdated - Corcod3L
0d 0h 08m 12s > CitadelStationProvider.FetchIDs - ESI lookup for 1022036649791 using 131775193314170258 (Corcod3L)
0d 0h 08m 13s > CitadelStationProvider.FetchIDs - ESI lookup for 1022318111012 using 131775193908531776 (Mirabela Tissant)
0d 0h 08m 13s > CitadelStationProvider.FetchIDs - ESI lookup for 1022888203840 using 131720565776278352 (DonFlorica Tissant)
0d 0h 08m 13s > CitadelStationProvider.FetchIDs - ESI lookup for 1022923119083 using 131720565776278352 (DonFlorica Tissant)
0d 0h 08m 14s > CitadelStationProvider.FetchIDs - ESI lookup for 1023736622218 using 131775193908531776 (Mirabela Tissant)
0d 0h 08m 14s > CitadelStationProvider.FetchIDs - ESI lookup for 1023736631383 using 131720565776278352 (DonFlorica Tissant)
0d 0h 08m 14s > CitadelStationProvider.FetchIDs - ESI lookup for 1023809940359 using 131775193908531776 (Mirabela Tissant)
0d 0h 08m 14s > CitadelStationProvider.FetchIDs - ESI lookup for 1024834036902 using 131720565776278352 (DonFlorica Tissant)
0d 0h 08m 15s > CitadelStationProvider.FetchIDs - ESI lookup for 1025943513790 using 131720565776278352 (DonFlorica Tissant)
0d 0h 08m 16s > CitadelStationProvider.FetchIDs - ESI lookup for 1026130391422 using 131775193908531776 (Mirabela Tissant)
0d 0h 08m 16s > CitadelStationProvider.FetchIDs - ESI lookup for 1026960906556 using 131775193908531776 (Mirabela Tissant)
0d 0h 08m 16s > CitadelStationProvider.FetchIDs - ESI lookup for 1027284517923 using 131775193908531776 (Mirabela Tissant)
0d 0h 08m 17s > CitadelStationProvider.FetchIDs - ESI lookup for 1028737718454 using 131775193908531776 (Mirabela Tissant)
0d 0h 08m 17s > EveMonClient.OnConquerableStationListUpdated
0d 0h 15m 03s > EveMonClient.OnServerStatusUpdated
0d 0h 15m 12s > EveMonClient.OnCharacterEVENotificationsUpdated - DonFlorica Tissant
0d 0h 18m 59s > EMDItemPricer.GetPricesAsync - begin
0d 0h 19m 05s > EMDItemPricer.OnPricesDownloaded - No result

**Comment by peterhaneve** [comment]
I believe that this issue has already been fixed in the yet unreleased version of EVEMon.
