### ISSUE TITLE
universe/names returns 404 on invalid ids

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#128]
Not sure if this is new behavior but https://esi.evetech.net/v2/universe/names/ returns a 404 response and no data if there is an invalid id in the array posted. 

In my case 145187431, 145205700, 145205710 and 145196648 where invalid ids. 

The ids being looked-up seem to be player names. This behavior makes this endpoint less usable for bulk lookup..

**Comment by peterhaneve** [comment]
This endpoint has always stated that it would error out if some of the names were invalid. However, I was under the impression that this error could never occur for player information. Even biomassed characters still exist, just part of <666>.

Has an actual scenario, using player names (not citadels or stations, those use another endpoint) triggered this in EVEMon?

**Comment by wvdvegt** [comment]
I'll have a look if i can trace the origin of the lookup.
