### ISSUE TITLE
Mailing lists causes #128 lookup failure.

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#129]
In mail items, the recipient is correctly handled based on the reciouent_type enum. But the sender is handled as if it where a player and scheduled for a lookup. 

In EveMailMessage.cs constructor the line:

            `m_senderName = EveIDToName.GetIDToName(src.SenderID);`

this should be handled by handling mailing lists separately (and maybe corporations/alliances as well if the GetIDToName() lookup does not handle them either).

Example JSON (note from and recipient are identical, both a mailing list):

```
[{
  "from" : 145205714,
  "is_read" : true,
  "labels" : [
  ],
  "mail_id" : 373285328,
  "recipients" : [
    {
      "recipient_id" : 145205714,
      "recipient_type" : "mailing_list"
    }
  ],
  "subject" : "TDF LOGI FITS",
  "timestamp" : "2018-10-31T09:05:00Z"
}]
```

**Comment by peterhaneve** [comment]
I tried a slightly simpler fix, which works if the character still is a member of the mailing list. If the character has since left the list, it will still fail, but I then added a check so it will show up as "Unknown".
