### ISSUE TITLE
Paused skill queue import sets skill points to incorrect value

### ISSUE THREAD

**Issue by wbSD** [peterhaneve/evemon#130]
This is actually really easy to reproduce, I am surprised nobody has noticed/reported it sooner.

You need a character with any skill which is level 3 or below. Add at least 2 levels of it to the skill queue, **make sure the queue is paused**, and then have the queue be imported via SkillQueue.Import
https://github.com/peterhaneve/evemon/blob/4ff64c04872fba9f7644af11f7741a65f858a276/src/EVEMon.Common/Models/SkillQueue.cs#L173-L190

Each skill in the imported queue is now processed, and a new QueuedSkill is constructed.
In the constructor, the character skill is found, and if the queue is paused, then the skill points of the character skill is set to the starting SP of the queued skill.

https://github.com/peterhaneve/evemon/blob/9baa928ed93ecdea27bfd6164afaeb898f1d16ee/src/EVEMon.Common/Models/QueuedSkill.cs#L21-L43

We have 2 levels of the same skill in the queue, so the starting SP of the first level is (probably) what the actual current SP is.
But when the second skill is processed, the character skill is updated to the starting SP of that level, which is off by up to an entire skill level.

The level of the character skill is not updated correctly, so some that shows the skill based on level will not look wrong, but for example in the plan window, if you have the current skill queue in the plan, you will notice that the first of those 2 levels either doesn't show in the plan, or shows a training time of (none).
![image](https://user-images.githubusercontent.com/1277455/49974343-fb0d3b80-ff38-11e8-864c-883debc8f419.png)

It doesn't matter if the import happens from ESI or the settings file, so this scenario can be reproduced even without querying ESI.

I can make the bug stop occurring by adding a sanity check to the QueuedSkill constructor, so that it compares the input skill level with the current skill level, before increasing the current skill SP.
Just added a `if (Skill.Level >= serial.Level - 1)` in front of this one line:
https://github.com/peterhaneve/evemon/blob/9baa928ed93ecdea27bfd6164afaeb898f1d16ee/src/EVEMon.Common/Models/QueuedSkill.cs#L43

**Comment by peterhaneve** [comment]
Given the number of old bugs like these that I can barely keep up with fixing, I am seriously considering a core rewrite of EVEMon.
