### ISSUE TITLE
Character reported as Alpha but it is Omega

### ISSUE THREAD

**Issue by twothe** [peterhaneve/evemon#131]
As in the title: did a fresh install of 4.0.9 (actually first install on this PC), loaded my character from ESI, everything works fine, except that it shows as Alpha while it is actually an Omega, thus double the skill-time all over the place.

**Comment by peterhaneve** [comment]
ESI has been acting up recently. If the condition persists, please add more details, since there are dozens of potential causes due to oddities in ESI.
