### ISSUE TITLE
No notifications displaying for any characters

### ISSUE THREAD

**Issue by Skymarshaller** [peterhaneve/evemon#132]

**Comment by peterhaneve** [comment]
ESI has had some issues in the last few days. Have notification worthy events actually occurred?

**Comment by Skymarshaller** [comment]
No notifications on this character but on several others there have been war declarations, citadel timers & skill completion notifications.

**Comment by peterhaneve** [comment]
Those notifications have already been fixed in the soon to be released version - CCP updated ESI which broke the previous URL.
