### ISSUE TITLE
Broken DPI scaling, toolbar icons gone ugly.

### ISSUE THREAD

**Issue by AnrDaemon** [peterhaneve/evemon#133]
Left is v3, right is v4.
Everything is right but toolbar icons and toolbar context menu.
Same monitor, system DPI 100%.
![20181221-085022-evemon](https://user-images.githubusercontent.com/6532485/50327350-c6345200-04ff-11e9-9b0a-e691bd8ad457.png)

**Comment by peterhaneve** [comment]
While this is unlikely to make a substantial difference, have you tried the different Windows DPI scaling modes? See https://www.windowscentral.com/how-improve-app-dpi-scaling-enabling-system-enhanced-feature-windows-10

**Comment by AnrDaemon** [comment]
Less than 100%?

**Comment by AnrDaemon** [comment]
I only really accept dot-for-dot scaling. Else my eyes begin to bleed.

**Comment by AnrDaemon** [comment]
Oh, modes. No, with 100% scaling, there's no difference between XP and Vista style DPI scaling.

**Comment by peterhaneve** [comment]
I found out how to make the toolbar match EVEMon v3, but the icons are now smaller and harder to click, particularly on touch enabled devices. The icons themselves are only 16x16 which makes it look ugly when blown up. Increasing the button size while leaving the icon at 16x16 makes a similarly bad looking toolbar with tons of empty space around each icon.
