### ISSUE TITLE
Virus found 

### ISSUE THREAD

**Issue by Sonnenwerk** [peterhaneve/evemon#135]
After downloading current version, Chrome investigates and a virus warning is given.

**Comment by peterhaneve** [comment]
According to [Virus Total](https://www.virustotal.com/#/file/a60504cfa4513c3c590325f67c9d9bdb209b87f5d1384b3ada8ea0022044aab7/detection), this appears to be a false positive. The binaries zip file works if Chrome does not fix the issue.
