### ISSUE TITLE
Upgrade fails

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#136]
Since quite some time i get an error when using the upgrade dialog. When i press the upgrade button i get a 'cant download' error. 
I'll try to find the cause (most likely is a wrong download directory i think).

**Comment by krasje** [comment]
Got the same error.

**Comment by kormat** [comment]
I wonder if this is related - when trying to download the release manually from github, chrome shows this:
![image](https://user-images.githubusercontent.com/6919822/50420971-d53a3d80-083a-11e9-9b2e-047c764e0637.png)

**Comment by wvdvegt** [comment]
That's not related (Edge does the same thing). Issues that are related:
1) The installed not being signed (which costs quite some money & effort to obtain a signing certificate). 
2) Windows (& Browsers) also keep a list of infrequently downloaded files (SmartScreen).

**Comment by wvdvegt** [comment]
Got the cause (but can't fix it, no write access to this GitHub repo).

The autopatchurl tag in the file **https://raw.githubusercontent.com/peterhaneve/evemon/master/updates/patch.xml** is not matching the download url. 

`<autopatchurl>https://github.com/peterhaneve/evemon/releases/download/4.0.10/EVEMon-install-4.0.10.exe</autopatchurl>
`
should read (note the .0 suffix in the path):
`<autopatchurl>https://github.com/peterhaneve/evemon/releases/download/4.0.10.0/EVEMon-install-4.0.10.exe</autopatchurl>`

Examining the releases (and their links), it seems like some have a suffix of 0. or .1 others do not. It seems caused by the release's tag having the same suffix.

Also a bit strange is that the xml file contains a newest tag that points to 4.0.9 (where i would expect it to be the latest version).

**Comment by peterhaneve** [comment]
Signing the installer is not worth the effort given the frequency of releases and the cost to obtain a code sign certificate. It also would have to be obtained under my real name unless I created a legal entity to own it, which would present numerous doxing opportunities.

The release tag behavior is inconsistent due to some issues in the PatchXmlGenerator.

**Comment by wvdvegt** [comment]
I agree, i tried to obtain a certificate 2yeras ago. It was pricey and failed because rules where tightened (you now need to buy a $100 security device to store them they told me). And you have to pay every year.
But signing makes quite a difference when installing software (at work i can code sign).
