### ISSUE TITLE
Adding support for Loyalty API?

### ISSUE THREAD

**Issue by IamTechknow** [peterhaneve/evemon#138]
I noticed that EVEMon currently does not support viewing a character's loyalty point balance. I think being able to view this information would be helpful, although it would require adding a new "advanced feature" in the UI as well making new API calls. I have worked with Java a lot but only a little with C#. I think I could work on a pull request for this, if you like.

**Comment by peterhaneve** [comment]
If you want to give this a shot, be my guest. I am currently working on other issues at the moment, but this would probably be best to start from the Standings or Contacts view.

**Comment by IamTechknow** [comment]
Thanks, I started it yesterday with what you suggested. So far it seems to be working out, I got a list to show up with the loyalty point data for my account. I got more things to do, then I'll be ready to send a pull request!

**Comment by peterhaneve** [comment]
Oops, meant to close a different issue with that commit, but since you have a PR out we will track it there.
