### ISSUE TITLE
Can't obtain token, cause scope `esi-corporations.read_outposts.v1` does not valid

### ISSUE THREAD

**Issue by marfenij** [peterhaneve/evemon#143]
this scope not exist anymore 
and on official swagger I don't see corp outpost 
https://esi.evetech.net/ui/?datasource=tranquility&version=dev#/

also found that problem https://github.com/roxlukas/lmeve/issues/81

**Comment by peterhaneve** [comment]
Did they delete a scope, without the slightest mention on https://developers.eveonline.com/?

**Comment by marfenij** [comment]
@peterhaneve thank you for ultra fast release 👍
