### ISSUE TITLE
Touch enabling dismissal of notifications

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#145]
To enable easier dismissal of the notifications above for instance the skill queue and at the bottom of the screen, i modified the last couple of lines In Notificationlist.cs / listBox_MouseDown() to:

```
                // Did the click on the "delete" icon or did a wheel-click?
                Rectangle deleteRect = GetDeleteIconRect(rect);
                if (e.Button != MouseButtons.Right)
                {
                    if (e.Button != MouseButtons.Middle && !deleteRect.Contains(e.Location))
                        continue;
                }
                EveMonClient.Notifications.Invalidate(new NotificationInvalidationEventArgs(notification));
                m_notifications.Remove(notification);
                UpdateContent();
                return;

```
The result is that the new touch code in the NoFlickerListBox that sends a right mouse click now ends up here and dismisses the notification when long tapped (or right clicked with the mouse, ignoring the close box).

Bit dirty fix (and it won't help showing the window from the magnifing class but personally i can live with that (then on smaller tables 3-4 hard to close notifications totally block the content view of the NoFlickerListbox).

A pro is that quite some mice do not have a middle button so the code using the middle button would not work for those anyway.

**Comment by peterhaneve** [comment]
Is the delete icon too hard to press otherwise? In my opinion long press to clear notification is not intuitive, and I did not even know that the notifications could be middle clicked to dismiss.

**Comment by wvdvegt** [comment]
Hi

Yes on a small tablet is takes me between 10-15 taps sometimes to hit it at all. The proposed fix makes it much easier (and right clicking with the mouse is also easier if you if not have a middle mouse button).
