### ISSUE TITLE
Blank character creation includes extra skills

### ISSUE THREAD

**Issue by dantetsaronis** [peterhaneve/evemon#147]
Blank character creation shows things like Acceleration Control 1 and Repair Systems 1 already trained, but new characters in game do not have these skills even injected.

Evemon version 4.0.11

I first noticed with my Caldari character, and @aschlot was able to verify it today by creating this character: https://esi.evetech.net/latest/characters/2114965222/?datasource=tranquility

Amarr race (4), Ni-Kunni bloodline (6), Border Runners ancestry (5), male gender.

Attached is the Evemon-generated CCPXML file from the blank character creation process, unmodified. Github doesn't accept XML attachments so it's zipped...

[evemon test 2019-02-16.zip](https://github.com/peterhaneve/evemon/files/2872272/evemon.test.2019-02-16.zip)

Big thanks to @aschlot for confirming this for me!

**Comment by peterhaneve** [comment]
The skill list for new characters was hard coded before I took over, and it appears that it has since changed. Unfortunately, there is no ESI endpoint for this data, and the updated NPE has changed the skill set.

The long term solution is probably to add the skills to the static data like was done with the alpha limitations. In the short term, are you aware of any differences between the races other than the gun and missile skills?

**Comment by dantetsaronis** [comment]
Looks like at least Racial Industrial 1? And I'm not so sure about the weapons, as this Amarr character has Missile Operation 1 and no small turrets at all.

Skill list here: https://eveskillboard.com/pilot/video_killed_theradiostar

**Comment by peterhaneve** [comment]
Do new Caldari characters get missile support skills instead of turret support skills?

**Comment by aschlot** [comment]
@peterhaneve I'll get a character up and running. Would it be helpful to have a Gallente / Minmatar example as well?

**Comment by aschlot** [comment]
Caldari receives the following missile skills:

- Missile Launcher Operation I

They receive the following Gunnery skills:

- Trajectory Analysis I
- Surgical Strike I
- Controlled Bursts II
- Motion Prediction II
- Sharpshooter II
- Rapid Firing II
- Gunnery IV

Skills for a new Caldari character:
https://eveskillboard.com/pilot/star_strucked

**Comment by peterhaneve** [comment]
It looks like the latest NPE rework unified skills to guns. Since this seems to be changing often due to frequent attempts to get the NPE right, is there an ESI endpoint or attribute for this data?
