### ISSUE TITLE
Small usability issue in blueprint/item browser

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#149]
Hi

Small usability issue (not causing an exception). Steps:

- Select something in the Item browser (so the search edit field is not empty)
- Close the dialog
- Open the blueprint browser, search for 'rorqual blueprint' for example and right-click a capital part needed for building this ship (Bill of Materials) and select 'Show in Item Browser' context menu option.

The result is that you briefly get to see the part but end up with a empty page with the text 'Use the tree on the left to select an item to view'. Expected would be to see the capital part in this example.

See the attached screenshots

![1](https://user-images.githubusercontent.com/1768983/53170795-4dc23e00-35e1-11e9-91f3-bd19b8b1d9b2.PNG)
![2](https://user-images.githubusercontent.com/1768983/53170811-574ba600-35e1-11e9-865c-ecb7f68dec7d.PNG)
![3](https://user-images.githubusercontent.com/1768983/53170822-5ca8f080-35e1-11e9-9b3a-fc3f2c818843.PNG)

**Comment by peterhaneve** [comment]
This one was actually difficult to reproduce as it was a race condition with the search timer. The fix was also not as easy as it looked since not all items which can be shown in the item browser actually appear in the item tree. After this change, the correct item should always be shown, but the search results might be inaccurate.

**Comment by wvdvegt** [comment]
Hi

Still can't get it to work (pulled the sources). The item text is ok but the description is missing (so like the third screenshot but with the correct text in the search field. The correct description is shown briefly.

Race timers are indeed nasty to debug as setting breakpoints totally ruins the timing.

**Comment by peterhaneve** [comment]
Oddly enough, I can only reproduce the exact opposite problem, as doing those exact same steps produces the wrong search field text but the correct item description!

**Comment by wvdvegt** [comment]
Got it: it was an unchecked 'show all groups' checkbox in the item browser I overlooked. It 

However typing in the search fields is very slow now (The longer the search string the slow it gets). Right clicking an 2nd item from the blueprint ingrediences takes around 20 sec on a very gast laptop before the items tab is shown. Performance seems to be tied to the 'show all groups' checkbox.
