### ISSUE TITLE
Show all groups checkbox slow

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#152]
Hi

In ItemSelectControl.cs the BuildTeeView() method takes around 4 seconds on a my development machine if the 'Show all groups' checkbox is being checked. 

Typing in the search box also becomes very slow (as if the tree is updated every keystroke). This typing slowness also happens in the blueprint browser if the checkbox is checked.

![image](https://user-images.githubusercontent.com/1768983/53810555-881fc980-3f57-11e9-82c9-2e903fcc3da9.png)

**Comment by peterhaneve** [comment]
EVE has so many items that it causes scalability issues with Windows Forms if all groups are shown. It would require a large rewrite to speed this up, probably involving incremental tree population.
