### ISSUE TITLE
Add option to display active industry job count

### ISSUE THREAD

**Issue by zhlzhl123** [peterhaneve/evemon#156]
Displacing the active job number or the remaining job in the overview could be very helpful.

**Comment by peterhaneve** [comment]
The overview is already very crowded, and for players with dozens of accounts it would slow down EVEMon. In what scenario would this be useful?

**Comment by zhlzhl123** [comment]
> The overview is already very crowded, and for players with dozens of accounts it would slow down EVEMon. In what scenario would this be useful?

I use this pogrom to track the skill of my characters, meanwhile I also use it to check my industry and copy jobs, to check whether there is remaining unused slot. It can be very convenient if I can get all this information from the overview instead of clicking into each page of all those characters.

Indeed the overview is crowded.  can we just add an option in the setting?

Thank you very much!!

**Comment by BrotherBloat** [comment]
Hi Peter!
Great job on this indeed! For some reason, my job count on all characters sits at zero on the main screen, while refreshing correctly on the per-character screens. I tried clearing cache and waiting for a refresh, to no avail. Have I spotted a bug?
Thank you once again! Stellar work!
