### ISSUE TITLE
"Toggle New Implant Set" in Skill Plan

### ISSUE THREAD

**Issue by rayanth** [peterhaneve/evemon#159]
Similar to the "Toggle Remapping Point" on the Plan Editor, there should be a "Toggle Implant Set".

Thoughts:

- It would permit players to pre-plan jump clones with different implant sets for different parts of the training queue, if necessary
- It would permit players who know they might be switching between alpha/omega at a certain point to change implant sets appropriately (see #158)
- It would permit players to add new implant set when their Cybernetics Skill reaches new levels in their current plan, such as allowing them to switch the plan to +4 implants when they hit Cybernetics 4, and +5 implants at Cybernetics 5.
- And also allow players who know they will be spending a predetermined time outside of a training clone to plan that time into their skill plans.

**Comment by peterhaneve** [comment]
This change would break compatibility of exported skill plans with older versions of EVEMon. Aside from this ugly obstacle, remap points could be changed to include jump clones easily, but the plan would break if the character destroyed the jump clone used to calculate the skill times.

**Comment by rayanth** [comment]
Valid points that I neglected to consider. Can't really think of a way around them, at the moment aside from maybe not including it in exports; but that would force the user to apply it each time they load up. The only other thing I can think of for trying to advance-plan Cybernetics learning (my ultimate goal here, for building plans for different types of skillfarming characters) and the changes to the ability to include better implants, would be to allow the user to force remaps beyond the maximum allowed by game, so they could mimic the effect of better implants in a Toggle-Remap point. 

Obviously this would require carefully alerting the user that they ARE past the game-allowed maximum (maybe by making the green tick marks turn to red when they go beyond?) but as an artificial means of adding the effect of better implants under current code, it's about all I can think of. I suppose that might break older versions of Evemon if a newer export is imported though.

**Comment by peterhaneve** [comment]
It might be possible to store the changes internally and not export them, but this would break when the plan was exported and re-imported on the current version. It might not be as relevant for say, alliance skill plans (which are a popular use case for EVEMon exported skill plans) but would also break least surprise.

`OutputPlan` inherits from `SerializablePlanEntry`, which stores an optional `SerializableRemappingPoint` which would need to be changed. Adding a simple field here would technically not immediately break backwards compatibility as the XML parser ignores unknown fields, but any changes to the skill plan in previous versions of EVEMon would destroy the implant information.
