### ISSUE TITLE
Skill Injector not showing

### ISSUE THREAD

**Issue by demonwolf1994** [peterhaneve/evemon#161]
iv updated to 4.0.11 but now it doesn't tell me how many Injector's it will take to complete the training at 1st it wold sowe now and then but it hasent for 2-3 weeks now

**Comment by peterhaneve** [comment]
Try expanding the skill plan window. A recent feature change shows the number of Large and Small Skill Injectors required, but this has the side effect of making the field much larger, which may have wrapped it onto the next line.
