### ISSUE TITLE
missing market orders

### ISSUE THREAD

**Issue by november781** [peterhaneve/evemon#162]
looking at my character's market orders, I am only seeing the orders in my fortizar and not orders that I have placed in Jita 4-4

![2019-04-12 08_29_09-Greenshot](https://user-images.githubusercontent.com/28309327/56040978-3f4cf480-5cfd-11e9-8422-0a1f4e0a8d2c.png)

In the above image, I am missing 3 buy orders from 4-4

**Comment by peterhaneve** [comment]
I was not able to reproduce this issue. Did you make these orders very recently? It could also be an ESI issue since the two order sets use different endpoints, do the orders appear now?

**Comment by november781** [comment]
I have had these orders on the market in 4-4 for several weeks and they are not showing in the app. New market orders that I have put up in my fortizar are showing.

**Comment by peterhaneve** [comment]
Do the market orders show up in the [ESI web app](https://esi.evetech.net/ui/#/Market/get_characters_character_id_orders)? If so, can you paste the (non-doxing) portion of the response?

**Comment by november781** [comment]
yes all orders appear in the ESI web app 

`[
  {
    "duration": 90,
    "is_corporation": false,
    "issued": "",
    "location_id": 1028842270975,
    "order_id": ,
    "price": 5999.99,
    "range": "region",
    "region_id": 10000042,
    "type_id": 47925,
    "volume_remain": 4500,
    "volume_total": 5000
  },
  {
    "duration": 90,
    "is_corporation": false,
    "issued": "",
    "location_id": 60003760,
    "order_id": ,
    "price": 1192999989.09,
    "range": "region",
    "region_id": 10000002,
    "type_id": 50149,
    "volume_remain": 1,
    "volume_total": 1
  },
  {
    "duration": 90,
    "is_corporation": false,
    "issued": "",
    "location_id": 60003760,
    "order_id": ,
    "price": 546999999.91,
    "range": "region",
    "region_id": 10000002,
    "type_id": 50147,
    "volume_remain": 1,
    "volume_total": 1
  },
  {
    "duration": 90,
    "is_corporation": false,
    "issued": "",
    "location_id": 1028842270975,
    "order_id": ,
    "price": 3799.99,
    "range": "region",
    "region_id": 10000042,
    "type_id": 20759,
    "volume_remain": 1000,
    "volume_total": 1000
  },
  {
    "duration": 90,
    "is_corporation": false,
    "issued": "",
    "location_id": 1028842270975,
    "order_id": ,
    "price": 177800187.99,
    "range": "region",
    "region_id": 10000042,
    "type_id": 19173,
    "volume_remain": 1,
    "volume_total": 1
  }
]`

**Comment by peterhaneve** [comment]
Today I learned that [required ID fields](https://esi.evetech.net/ui/#/Market/get_characters_character_id_orders) in ESI can be empty. Thanks a lot ESI.

`"location_id":1028842270975,"order_id":,"price":5999.99`

There is really nothing I can do here - ESI is violating its own Swagger spec, and orders are primary keyed by their ID in EVEMon so giving them a random or autoincrementing ID would break the interface when (if) they ever get proper IDs. Consider opening an issue on https://github.com/esi/esi-issues/issues.

**Comment by november781** [comment]
order id was removed by me, I am not sure what all that data can be used for. Swagger had all the required fields

**Comment by november781** [comment]
here is the complete file
[response.txt](https://github.com/peterhaneve/evemon/files/3090558/response.txt)

**Comment by peterhaneve** [comment]
These orders all have type IDs of new items not in the EVEMon database, so the orders will not be displayed as EVEMon has no clue what you are selling or buying. The database will not be updated until the [CCP SDE] (https://developers.eveonline.com/resource/resources) is released, but this file has not been updated since February.

Hopefully CCP will not forget about this file, since it also contains important attribute updates used by both EVEMon and EFT. If CCP discontinues providing this file, it will take a pretty big effort to recreate it from the ESI data (and probably tens of thousands of requests for each EVEMon release to fill out all the data).
