### ISSUE TITLE
COMException in ReadingPane.cs at Evemon startup

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#164]
Hi

I got a COMException in the designer code of ReadingPage.cs at the line:

[this.wbMailBody.AllowWebBrowserDrop = false;](url)

I moved this line from the designer code (called by InitializeComponent in the constructor) and moved it to the UpdatePane() method just after the lines 82-86 like:

```
do
{
                Application.DoEvents();
} while (wbMailBody.IsBusy);

this.wbMailBody.AllowWebBrowserDrop = false;
```

Note: If you want to put the line earlier in this method you could set the url to about:blank and wait for it to load, then set AllowWebBrowserDrop and set the wbMailBody.DocumentText and wait for that.

As a good measure i often use about:blank as the designer value for WebBrowser.Url.

**Comment by peterhaneve** [comment]
This flag should be set to false since there is no need (and is in fact a potential security risk) to allow dragging of documents into EVEMon's reading pane. What is the exception text? According to the documentation for `AllowWebBrowserDrop`, `COMException` is not even throwable here.

**Comment by wvdvegt** [comment]
It's setting the AllowWebBrowserDrop that causes the issue. It's a known .Net WebBrowser issue. 

Seen this issue before in my own .Net software. I think there should be a page loaded (so the WebBrowser be initialized and have a parent etc.) before the property can be set (so it cannot be set at design-time).

Loading the 'about:blank' url and wait for it and then set the property and then move to a new page is a workaround. It has the benefit the old page is cleared before loading a new one.

The COM exception is the only exception i see besides some that Evemon throws because the emergency patch xml cannot be retrieved.
