### ISSUE TITLE
invalid_request when adding Characters

### ISSUE THREAD

**Issue by infinityhacks** [peterhaneve/evemon#165]
{"error":"invalid_request","error_description":"Invalid state for character selection."}

**Comment by peterhaneve** [comment]
I was not able to reproduce this issue. It is possible that the recent [ESI downtime](https://eve-offline.net/) was the cause. Did it occur before or after you logged in? Did you get a chance to select a character to addd?

**Comment by infinityhacks** [comment]
This is the first time I try to use this branch of EVEMON.

The error occurred after I login with sso, then the redirected page showed the error above

**Comment by peterhaneve** [comment]
If the error is displayed in between logging in and selecting a character, the issue is outside of EVEMon, as control is not returned to the internal web server until a character is selected.
