### ISSUE TITLE
Allow automatic export to CSV

### ISSUE THREAD

**Issue by squigglezworth** [peterhaneve/evemon#168]
It would be great if EVEMon were able to automatically export certain data to a CSV at certain times, for use in other applications.

Personally, I'm exporting the wallet journal to a CSV regularly, and importing it into Excel to show various summaries, such as daily Bounty Prizes.

It would also be great if we could update the wallet journal more often than 1 hour, though I'm not sure if this is a limitation of EVEMon or EVE's API

(Thank you for creating an awesome tool)

**Comment by peterhaneve** [comment]
This feature is outside of the scope of EVEMon. However, parsing the EVEMon settings file (XML format) will allow external tools to generate such a report without too much trouble.

Some update intervals can be adjusted through the settings page. However, the ESI cache timer limits the minimum value which can be used in the settings.
