### ISSUE TITLE
Upgrade to .NET Core 3.0

### ISSUE THREAD

**Issue by rogersachan** [peterhaneve/evemon#169]
As .NET Core gets closer to GA I think support for it should be explored since it provides cross platform support and performance boosts. Not to mention that migration will be necessary when .NET 5 is released.

In moving I found these resources useful:
- https://github.com/hvanbakel/CsprojToVs2017
- https://devblogs.microsoft.com/dotnet/how-to-port-desktop-applications-to-net-core-3-0/
- https://docs.microsoft.com/en-us/dotnet/core/porting/wpf

**Comment by peterhaneve** [comment]
What would this upgrade accomplish for EVEMon?

**Comment by rogersachan** [comment]
@peterhaneve [Microsoft claims](https://devblogs.microsoft.com/dotnet/net-core-3-and-support-for-windows-desktop-applications/) that this update brings "More deployment flexibility, Core Runtime and API improvements and also more performances." By the time the .net framework EOLs and .NET 5 releases a migration will be necessary.

**Comment by peterhaneve** [comment]
According to https://devblogs.microsoft.com/dotnet/update-on-net-core-3-0-and-net-framework-4-8/ the regular .NET Framework will not go end of life. The backwards compatibility with older Windows versions (particularly 7) also seems to be a bit checkered. This might be in scope for EVEMon 5 but porting version 4 is unlikely to be worth the effort.
