### ISSUE TITLE
Add option to display active researching job count

### ISSUE THREAD

**Issue by zhlzhl123** [peterhaneve/evemon#170]
Hi, thanks you for adding option to display active industry job count at #156.
However, it is possible to add this information for both researching job and reaction job count?
It could be really convenient if all of them can be displaced at the same time.
Thanks

**Comment by peterhaneve** [comment]
There is not enough room for all job types at once. Showing one selected type would be feasible but would probably not match the intent. I could try a tooltip but again that would gain little over clicking on each character.

**Comment by zhlzhl123** [comment]
> There is not enough room for all job types at once. Showing one selected type would be feasible but would probably not match the intent. I could try a tooltip but again that would gain little over clicking on each character.

Thank you.
I think, for now, the job count "0/10" fit really well will the overview.

How about adding an option to show just the remain job for industry, science and reaction counts in order, like "1 0 10" instead of "1/10 0/10 10/10". It can save a lot of space although it could be a little bit hard to understand.

**Comment by peterhaneve** [comment]
"1 0 10" would not make sense to most users. If you are really into industry, have you tried another tool like EVE ISK Per Hour?

**Comment by zhlzhl123** [comment]
> "1 0 10" would not make sense to most users. If you are really into industry, have you tried another tool like EVE ISK Per Hour?

Well, it could make sense if there is description near the option in the setting. If those users don't need this function, they can just don't turn it on >_< And the users who turned it on, they must know the meaning these number. You can use different color to represent them as well (yellow->industry, blue->science, green->reaction)

I have tried a lot of tools, but only yours contain exactly what I need and display them well and clear!!
I like it so much, I just want it to be a little more perfect :)

**Comment by BrotherBloat** [comment]
Agreed - no other tool compares. IPH is great for industry, but isn't really geared to give the "at your fingertips, always on" kind of info! EVEMon is the only EVE tool I let autostart!

**Comment by peterhaneve** [comment]
How about cycling through the job types every few seconds? Color coding will not work well with color blind folks or the "safe for work" mode though.

**Comment by BrotherBloat** [comment]
> How about cycling through the job types every few seconds? Color coding will not work well with color blind folks or the "safe for work" mode though.

that would work beautifully! However, I seem to have some sort of a glitch where the job counts don't display on any toons. they appear OK in the manufacturing tabs on each of them, though!

**Comment by zhlzhl123** [comment]
> How about cycling through the job types every few seconds? Color coding will not work well with color blind folks or the "safe for work" mode though.

It is possible to add a tool in the "Tools" option which can displace a list of characters with their maximum jobs numbers and the current job numbers, including manufacturing, research and reaction?
