### ISSUE TITLE
Unable to disable HTTP Proxy

### ISSUE THREAD

**Issue by dataphreak1001** [peterhaneve/evemon#171]
Because I am at work, we have an HTTP proxy built into IE for our intranet. I would like to be able to disable the HTTP Proxy, rather than using the IE proxy by default. This prevents me from using the program, as I have no alternate HTTP Proxy to enter.

**Comment by peterhaneve** [comment]
Fixed in 7eb6911 by causing blank proxy (enabled but host is empty) to use "no proxy" even if IE specifies one.
