### ISSUE TITLE
Corporate contracts

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#172]
Hi

It seems like corporate contracts do no longer show up in the list of contracts.
They however create a message that they need attention, but the details dialog remains empty.
When I delete the contracts from the setting xml file they show up correctly until I restart EveMon. Almost looks like wrong id's are written.

**Comment by wvdvegt** [comment]
In Fiddler I see the corporation contracts being retrieved correctly from eve esi.

**Comment by peterhaneve** [comment]
Are contracts made to a corporation affected, or those made on behalf of a corporation?

**Comment by wvdvegt** [comment]
Contracts on behalf of a corporation.

**Comment by peterhaneve** [comment]
EVEMon only stores skeletal information about all contracts in the settings file, and that is all which it has available if the ESI cache timer is still ticking. Unfortunately, I cannot add all of the required information to make it work properly without breaking backwards compatibility.

**Comment by wvdvegt** [comment]
Hi
It seems likte it's not 100% fixed yet. It 'works' if I remove the <contracts> tag and EveMon retrieves new data from scratch. 

When I restart only personal issued contracts are shown (the data in settings.xml is still correct), two corporate 'ItemExchange' contracts are missing.

Restarting EveMon yet again gives the info message again: '2 contracts finished or needs attention'. In the settings.xml these two contracts show up as 'Expired' instead of 'Created'.

**Comment by peterhaneve** [comment]
It cannot be 100% fixed without breaking compatibility with settings files from earlier versions of EVEMon.
