### ISSUE TITLE
https://esi.evetech.net/v3/universe/names/ issue

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#173]
Hi

I see a call to https://esi.evetech.net/v3/universe/names/ with a lot of ids that returns an error {"error":"Ensure all IDs are valid before resolving."}.

Because all ids are requested in bulk (understandable), none of them get resolved as a result. There is also no fallback to requesting them one by one in order to be able to skip the faulty one.

**Comment by peterhaneve** [comment]
Which IDs are failing? I tried closed corporations (still worked) and biomassed characters (also no issue). I remember a problem with assets in POCOs which may be related.

**Comment by wvdvegt** [comment]
That is exactly the issue, the call retrieves a 50 or more in one call. One of them is wrong. I'll try to catch the id's and do some binary search in them using the eve esi web interface.

**Comment by wvdvegt** [comment]
Some ids that go wrong. Given the range (https://docs.esi.evetech.net/docs/id_ranges.html) it should be older characters/corporations :
[ 145187431,145205710,145205712,145205714,177792443 ]
[ 145205712 ]
[ 145187431,145205700,145205710,145205714 ]
[ 145205700 ]

**Comment by peterhaneve** [comment]
https://esi.evetech.net/latest/characters/145187431/?datasource=tranquility returns "Invalid character ID"
https://esi.evetech.net/latest/corporations/145187431/?datasource=tranquility returns "Corporation does not exist!"
https://esi.evetech.net/latest/alliances/145187431/?datasource=tranquility returns "Alliance not found"

I am curious to know where this ID was referenced. EVEMon's approach is to avoid ever requesting invalid IDs in the first place.

**Comment by wvdvegt** [comment]
Seems to be the id of an incursion mailing list (TDF-SSS VG1). 
The entry shows up twice in a file called tdf_names.xml. Once with a name 'Unknown', once with a name (at the end of the file).

Removed the 'Unkown' duplicates to see what happens -> The mailing lists show up fine now.

So it seems that there where some (old) duplicate entries in the tdf_names.xml file of which the oldest ones where still Unknown. These names can only be resolved by supplying a character id as well. These are the correct names.
```
    <entity ID="145187431" name="TDF-SSS VG1" />
    <entity ID="145196648" name="TDF-Fits" />
    <entity ID="145205700" name="TDF-IMPLANTS" />
    <entity ID="145205710" name="TDF-FITS VG1" />
    <entity ID="145205712" name="TDF-FITS HQ1" />
    <entity ID="145205714" name="TDF-FITS LOGI1" />
```
So you probably should try to exclude these entries from being send to the universe/names endpoint and retried as it prevents the lookup of other id's in that batch. And maybe check why there are duplicates at all in the tdf_names.xml file.

**Comment by peterhaneve** [comment]
EVEMon does not contain any references to a file with this name, and `EveIDToName.xml` uses a dictionary key which cannot have duplicates. Where is this file specified?

**Comment by wvdvegt** [comment]
It's located in %appdata%\evemon. 
My guess it's named '<nameoflist>_names.xml' so one of such file for each mailing list.
The id's cannot be added to EveIDToName.xml i think because they overlap with other ranges.

**Comment by peterhaneve** [comment]
There are no references in EVEMon's mailing list code to save IDs separately. There is also no path to `SaveXMLAsync` which could ever contain a file with this name.

**Comment by wvdvegt** [comment]
Strange, when I delete the tdf_names.xml nothing changes. Maybe a left-over of something. 

The id's are present in the EveIDToName.xml file as well (and keep showing up in the UI).

**Comment by peterhaneve** [comment]
Many entities in EVE can be renamed, so an attempt is always made to resolve IDs to names again on each load. If you were a member of these mailing lists at one time (thus references occur in your EVE mails), yet you cannot access them any longer, then lookups might fail.

However, bisecting and retrying upon failure would be a large rewrite of the entire ID to Name service, due to the multi-tier structure (especially for structures) used to consult both ESI and a third party lookup service.

**Comment by wvdvegt** [comment]
Yes, EveMon accumulates the id's to lookup (from my understanding of the code). Rewriting that is a lotta work I think. 

I think you already try to prevent a regular lookup by resolving them with the mail / mailinglist endpoints. 

Then the only thing that might be doable is put them on a blacklist for subsequent periodic regular name lookups.
