### ISSUE TITLE
Tabs not working in portrait mode

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#174]
When i turn by 7" tablet in portrait mode, the tabs no longer work (they don't respond to a tapping them in order to switch pilots). 

Turning back to landscape makes them respond again..

**Comment by wvdvegt** [comment]
Hi

Tested it on my tablet, but it still fails to respond to taps. 
Mouse clicks with a virtual mousepad now work.

**Comment by wvdvegt** [comment]
Some observations:
1) I tried remote debugging on my Tablet but somehow EveMon does not allow it (some deserialization errors in the async start, when it executes UpdateManager.DeleteInstallationFiles).
2) Rotating the touch monitor of my development desktop results in all tabs being tapable so working as designed.
3) I also very often get the Portrait context menu when i try to tap the leftmost tabs, as if the image obstructs something. 
4) Tapping the portraits on the Overview shows the correct tab, so that is a workaround.

I'll continue to try to remotely debug when i have some time.

**Comment by peterhaneve** [comment]
Without buying a tablet I have no way of reproducing the issue, as it does not reproduce when manually rotating or resizing the screen.
