### ISSUE TITLE
Postbuild Event

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#176]
Hi

There seems to be an issue in the post-build event of EveMon.csproj regarding spaces in paths

I think these commands should read:

```
if exist "$(ProjectDir)EVEMon.res" del "$(ProjectDir)EVEMon.res"
if exist "$(TargetDir)EVEMon.exe.config" del "$(TargetDir)EVEMon.exe.config"
if exist "$(TargetDir)stdole.dll" del "$(TargetDir)stdole.dll"
```
And maybe should be moved to the pre-build command. I'm not sure what is being tried to accomplish here.

Sorry for keeping you at work ;-)

**Comment by peterhaneve** [comment]
I quickly found out in 58a888e that there are multiple issues which occur if built in a directory with spaces (particularly when building the installer). Given how easy the workaround is, I decided that hunting all of them down was not worth my time.
