### ISSUE TITLE
add better control over Manage Characters

### ISSUE THREAD

**Issue by mingsan303** [peterhaneve/evemon#177]
on Manage Characters menu window it would be convenient if added functions like select all, deselect all, by column sorting, group creation so you can group the related characters to that group

I have like 70+ characters which is very inconvenience to manage without those functions

i am using skillq.net at the moment for that but i dont want to use 2 apps

**Comment by peterhaneve** [comment]
The Manage Characters window uses a custom renderer, which makes all of these features very difficult to implement. Characters can be reordered on the overview screen, and grouped using custom labels, which may help somewhat.
