### ISSUE TITLE
Length of omega added to the overview?

### ISSUE THREAD

**Issue by mike0891** [peterhaneve/evemon#179]
Could the length of omega be added to the overview? Even if this is me manually adding it when I re-plex an account.  

Having this as an option on the extra info would be a lifesaver for me and I am sure many other people with many accounts with different plex dates.

**Comment by peterhaneve** [comment]
The ESI API does not have an endpoint for omega status. One option would be to enter the expiration date in the custom label field, which can also be rapidly copied across many characters if accounts are subscribed in bulk.
