### ISSUE TITLE
[Bug] 'queued' colour in plan view doesn't apply properly

### ISSUE THREAD

**Issue by esheyw** [peterhaneve/evemon#185]
Pretty much what the title says, in plan view, 'currently training' gets applied properly, but 'queued' seems not to be. Every skill that's both on the plan and in the current skill queue should be that colour, right?

**Comment by peterhaneve** [comment]
Since EVEMon 3, that color has only been applied to the skill currently training. It may be possible to have a different color for skills in the queue.
