### ISSUE TITLE
BPO issues

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#186]
Hi

Got two issues (maybe related):

1) At startup an exception in IndustryHob.GetOutputItem(), the BlueprintActivity.Manufacturing case where InstalledItem is null.
2) I installed the new Industrial Cyno bpo as a corporate job and see no corporate jobs. My guess it that the cyno is missing in the static data and the program does not handle it well and aborts decoding jobs.

Note: I just got & installed the database update, this fixes it after EveMon updated industry.

**Comment by peterhaneve** [comment]
Both issues are caused by outdated SDE data. If thr issue persists, please file a new issue with the troublesome item.
