### ISSUE TITLE
Small issue

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#187]
I encountered an exception on EveFlags.GetFlagText() because a_eveFLags was not null but did not contain the id key.

I changed 

```
            if (s_eveFlags != null)
                flag = s_eveFlags[id];
```

into

```
            if (s_eveFlags != null && s_eveFlags.ContainsKey(id))
                flag = s_eveFlags[id];
```

which fixed it. However no clue what caused it in the first place and what the EveFlag class is ment for.

**Comment by peterhaneve** [comment]
This issue is caused by the introduction of new flags. Flags are not exposed in ESI so I will have to manually trawl through the data and figure out what was added.

**Comment by peterhaneve** [comment]
After searching the SDE, I could find no references to new flags. Thank you very much CCP. While I have added a fallback if a flag could not be found, some functionality of EVEMon might be limited until new flags are included in the SDE.
