### ISSUE TITLE
Sorting LP list

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#190]
Can you add sorting to the LP listview? 

It seems like currently it's sorted on corporation id (as it's neither on name nor LP).

**Comment by peterhaneve** [comment]
The LP list view is now automatically sorted descending by LP earned. Unfortunately the LP UI was taken from the contacts UI and would be difficult to add custom sorting, but this mode is the most likely to place relevant corporations and factions at the top for players.
