### ISSUE TITLE
no notification for market orders

### ISSUE THREAD

**Issue by hollo6** [peterhaneve/evemon#196]
hi,

I don't receive any notifications when market orders are fulfilled. I get them for everything else (industry jobs completed, skill training completed, PI idle, etc.) but not for market orders, despite that the orders are there (the main window shows the orders correctly and notices the changes in them - at least if I get it right, turning the row light blue means that the order has changed).

**Comment by peterhaneve** [comment]
The notification only occurs when the orders expire, or are completely fulfilled; notifications are not generated for orders that are merely modified in price or partially fulfilled.

**Comment by hollo6** [comment]
Yes, that's what I would expect. I wanted a way to track expired and fully fulfilled orders but I never get any notifications for any orders.

**Comment by hollo6** [comment]
Is there anything I can do to help trace/debug this problem?
I've tried changing a lot of different parts of the code but this seems to be too diverse for trial and error debugging since it's not easy or quick to reproduce.
If you could make a debug build with breakpoints or debug printouts all over the relevant parts I'd be happy to test it, or I'm open to other ideas if you have any. I need this feature so badly... :)

**Comment by hollo6** [comment]
Thank you for the fix! Is it possible to have these orders remembered between sessions? Now if I restart the client, it sends a notification with the number of expired/fulfilled orders, but the details window is empty so I can't tell which those orders are.
