### ISSUE TITLE
Osmium-ZKB

### ISSUE THREAD

**Issue by Xou6upk** [peterhaneve/evemon#197]
Im sorry for my bad english,but could you replace Osmium to ZKB fits in loadouts?TY 0/
![git](https://user-images.githubusercontent.com/33947627/71319345-26acf500-24ae-11ea-9143-8e76fbd21e30.jpg)

**Comment by peterhaneve** [comment]
Zkillboard does not have an API endpoint which is directly comparable to the Osmium loadouts page. Rewriting this feature probably is not worth the effort, but efforts to integrate EVEMon with another site are in progress.
