### ISSUE TITLE
[Request] Add "Maximize Plan" using "Loadout import..." command

### ISSUE THREAD

**Issue by Tharnadar** [peterhaneve/evemon#198]
While using the "Loadout import..." would be nice to have a checkbox that maximize to level 5 all the skills involved for the loadout in clipboard memory, not only the missing skills, but also the skill already trained that affect every modules functionality.

**Comment by peterhaneve** [comment]
This functionality should be possible in fitting tools like PyFA and EFT. EVEMon does not have a full Dogma engine capable of listing every skill that affects a module / ship, and adding one is probably outside of the scope of EVEMon's static data export.
