### ISSUE TITLE
Market order expired or fulfilled

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#199]
Evemon is after the latest commit almost spamming me with 'n market orders expired or fullfulled' messages that when i click the magnifying glass turn up empty. 

In game i can't find anything either.

**Comment by wvdvegt** [comment]
It seems that the number is equal to the number of outstanding market orders.

**Comment by peterhaneve** [comment]
I was not able to reproduce this issue. It may be due to a race condition where an empty order list is initially imported for some reason, but then replaced with the correct list.

**Comment by peterhaneve** [comment]
I tried to find out why no order displayed in the window, and unfortunately the removal of expired and fulfilled orders from ESI (even though a status field still exists for them) means that it is no longer possible to determine the item that was being sold. The item sold and station was not written to the local settings in previous versions, and adding that now would break backwards compatibility.
