### ISSUE TITLE
Market orders

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#200]
I think i found a solution to the messages about market jobs being expired.
You import both for character and corporation where character contains the character jobs, both private and marked as issued for a corporation.

Therefor an import for corporation is no longer required (it only contains all the corp jobs by all corp members which you do not show as a single list anyway). They seem to be tailored to the Eve Market Order UI.

I changed the EveMon code  in CorporationDataQuerying.cs simply to this:

```
 private void OnMarketOrdersUpdated(EsiAPIMarketOrders result)
        {
            var target = m_ccpCharacter;

            // Character may have been deleted since we queried
            if (target != null)
            {
                //! veg Disabled as data also surfaces for characters.
                //var endedOrders = new LinkedList<MarketOrder>();
                //target.CorporationMarketOrders.Import(result, IssuedFor.Corporation,
                //    endedOrders);
                //target.CorporationMarketOrders.Import(new EsiAPIMarketOrders(), IssuedFor.Corporation,
                //    endedOrders);
                //EveMonClient.OnCorporationMarketOrdersUpdated(target, endedOrders);
            }
        }

```

**Comment by peterhaneve** [comment]
While it is true that the corporation market orders do not need to be queried, they are not the root cause behind the market orders expiring message. Disabling the code will stop some spurious failed request errors.
