### ISSUE TITLE
Expired market orders not remembered between sessions

### ISSUE THREAD

**Issue by hollo6** [peterhaneve/evemon#201]
Is it possible to have the expired/fulfilled orders remembered between sessions? Now when I start the app, it sends a notification with the number of expired/fulfilled orders, but the details window is empty so I can't tell which those orders are (the ones that got expired while the program was not running). Should work like industry jobs.

**Comment by peterhaneve** [comment]
Unfortunately this change is not possible without breaking backwards compatibility with previous versions of EVEMon. However, a workaround may be possible with the historical market orders endpoint.
