### ISSUE TITLE
Hypercores transaction missing from wallet

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#208]
Not sure if this is an API thing but I recently sold an item using hypercores and the transaction (and tax) are missing from the wallet and journal. 

Result is that the balance in the journal listview does not match the player's ISK balance shown in the character info above.

**Comment by peterhaneve** [comment]
I took a look at https://esi.evetech.net/ui/#/Wallet/get_characters_character_id_wallet_journal but there is no value in the enum for HyperNet. Therefore, it looks like CCP forgot to add this transaction type to the data the endpoint returns, and thus it is not possible for EVEMon to show it until that is fixed.

**Comment by wvdvegt** [comment]
Strangely, Eve Portal is however able to show them.

**Comment by peterhaneve** [comment]
https://github.com/esi/esi-issues/issues/1171 this is a confirmed ESI issue.
