### ISSUE TITLE
"market orders expired or fulfilled" on App startup provides a blank list.

### ISSUE THREAD

**Issue by GoingOffRoading** [peterhaneve/evemon#213]
EVEMon is correctly detecting that sell orders now have 0 quantities on app startup:

![Annotation 2020-04-10 155232](https://user-images.githubusercontent.com/4582826/79028035-6f62e980-7b43-11ea-8b7c-c4963d8bc999.png)

But the notification details is blank:

![Annotation 2020-04-10 155256](https://user-images.githubusercontent.com/4582826/79028021-5e19dd00-7b43-11ea-8e41-49602c4b11fd.png)

This issue is only with the market orders.  The other notification detail buttons work as expected:

![Annotation 2020-04-10 155406](https://user-images.githubusercontent.com/4582826/79028071-95888980-7b43-11ea-8943-bc07d0cd7720.png)

running 4.0.15 (64 bit)

I don't see any obvious menu for logs so let me know if I can help track this issue in any other way.

**Comment by peterhaneve** [comment]
This issue is due to the same root cause as #205.

**Comment by GoingOffRoading** [comment]
I'll follow that ticket.  Thanks!
