### ISSUE TITLE
Missing PI and Contracts (and others)

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#219]
I think the missing PI is caused by caching

When EveMon requests /v1/characters/<pilotid>/planets

ese.evetech.net returns a 304 not modified (and no data to process). Ideally EveMon should cache the data and use it's own copy instead.

I think removing the If-None-Match/Id-Modified-Since headers for the first request might help 

**Example: for one of my pilots I see a 304 status code on personal industry jobs while he a) has personal industry jobs and b) the tab is still empty.**

I will experiment a bit more to pin this issue down.

**Comment by wvdvegt** [comment]
I removed all tags inside <lastUpdates> in the settings.xml.

For all accounts I see queries to /v1/characters/[pilotID]/planets/ and 200 response codes with data.

However: for two pilots I see planetary info (the requests have no If-None-Match/Id-Modified-Since headers), the others are not queried at all. 
The two pilots who show PI belong to different accounts. Others in these accounts remain blank.

Next I cleared all <LastUpdates> and <Contracts> which should force EveMon to refresh it's data.
Again as reported earlier, most pilots show Finished contracts but not all that are present in the settings.xml and no created ones. One pilot shows a created and two finished contracts. All contracts are for character.

Still no clue what's causing it.

When I look with Fiddler to the traffic, the response to /v1/characters/[pilotID]/contracts/ contains the same info as stored in settings.xml including two created contracts that do not show up in the contracts tab. Internal data in EveMon seems ok (as far as I can tell), it's just not shown.

**Comment by wvdvegt** [comment]
Think I got the spot where PI goes wrong !!!

For some pilots I do not see any follow up after /v1/characters/[pilotID]/planets/.

In handling this request using PlanetaryColonyCollection.Import, new PlanetaryColony objects are created.

However in the constructor of this method the SolarSystem stays null (i.e. `SolarSystem = StaticGeography.GetSolarSystemByID(src.SolarSystemID); `
fails) .

Then it runs unto an exception when retrieving the PlanetName some lines below in the same constructor. The first SolarSystemID failing is 30003052.

The line causing the exception is:
`PlanetName = SolarSystem.FindPlanetByID(PlanetID)?.Name ?? EveMonConstants.UnknownText;`
which fails if SolarSystem is null.

The error (if I add a ? after SolarSystem so missing planets become UnknownText propagates a bit further into CharacterPlaneraryList.UpdateContent() where the SolarSystem name of the colony cannot be retrieved for the groupText because SolarSystem is null.

**Comment by wvdvegt** [comment]
I had a quick look at the eve-geography-en-US.xml.gzip files. The latest one is half the size of the old one. 

Restoring the old backup gzip immediately 'fixes' the issues.

**Comment by peterhaneve** [comment]
It looks like CCP provided a defective SDE (really?). I will restore it with a datafiles update.
