### ISSUE TITLE
Downloading images

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#220]
It seems like character portraits and corporate/alliance logo's are downloaded from the wrong server at several places. 

For example public Image CorporationImage in Loyalty.cs uses GetImageAsync/GetImageUrl that generates url's based on NetworkConstants.CCPIconsFromImageServer.

The new style URL's are:
`Uri uri = new Uri($"https://images.evetech.net/corporations/{CorpId}/logo?tenant=tranquility&size={(int)EveImageSize.x128}");`

And (untested):
`Uri uri = new Uri($"https://images.evetech.net/akkiances/{AllianceId}/logo?tenant=tranquility&size={(int)EveImageSize.x128}");`

Similar URL's can also be used in ImageServices.GetCharacterImageAsync , GetAllianceImageAsync and GetCorporationImageAsync.

**Comment by wvdvegt** [comment]
It also seems the image is downloaded multiple times. 

Example:  ImageServices.GetCacheName(Uri url), where GetMemoryStream retrieves the image once more.

This method is also incorrect with the new URL scheme (the image extension is very likely stored in a http header instead of in the URL itself).

**Comment by wvdvegt** [comment]
Employment history has a similar corporate logo issue (none of them show up).

**Comment by wvdvegt** [comment]
Contacts and Standing are also showing default images so seem to have the same issue.

**Comment by VixenVix** [comment]
I have a lot of 400 status codes in trace.txt
 `EVEMon.Common.Net.HttpWebClientServiceException: A request to image.eveonline.com failed with status: 400 (Bad Request).`
