### ISSUE TITLE
Research tab incomplete

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#222]
For all my pilots I see either 2 or 4 research agents but never the 5 it should be for all pilots (to be sure using the latest binaries from EVEMon-binaries-4.0.16.zip).

**Comment by dekeonus** [comment]
adding a me too, however I've only one character doing R&D and they have no agents presented (was working fine in 4.0.15)

**Comment by wvdvegt** [comment]
Might be caused by #219 (the static data related issue).

**Comment by peterhaneve** [comment]
Yes this is due to a defective CCP SDE. The latest data update appears to be correct however.
