### ISSUE TITLE
Forcing omega causes crashes on my system.

### ISSUE THREAD

**Issue by marethmin** [peterhaneve/evemon#228]
I can force omega and it works for a current plan. As I attempt to manipulate a plan or put together a new one on a "force omega" character(on multiple characters, instances and reboots) evemon crashes with in a few minutes. Thanks for all of your efforts!

[EveMon crash-technical details.txt](https://github.com/peterhaneve/evemon/files/4535234/EveMon.crash-technical.details.txt)

**Comment by peterhaneve** [comment]
While I was unable to reproduce this issue, f48b1eb does fix a potential crash in this view that could occur with empty skill group IDs.
