### ISSUE TITLE
Market notifications - item mismatch?

### ISSUE THREAD

**Issue by ozbird** [peterhaneve/evemon#229]
I've been selling items in Jita, and receiving notifications for sales - but the items reported don't match what I sold (e.g. I did not sell Omber or Valkyrie I drones.)

I'm not sure if the item names are just wrong, or if I'm seeing someone else's sales.

I've just listed a bunch of Aurora Universalis SKINs, so I'll see what the notifications say for those.

**Comment by hollo6** [comment]
Same as #224, still happening for me too. Mostly when ESI is having issues.

**Comment by peterhaneve** [comment]
Please track any

**Comment by ozbird** [comment]
I don't think this is a caching issue.

The sold items notification seems okay, but fulfilled items is nuts.
e.g. I have one item currently listed, which hasn't sold - yet I received a notification for 65 fulfilled items including ones I don't think I've seen before, let alone listed for sale.
