### ISSUE TITLE
Cannot retrieve character info

### ISSUE THREAD

**Issue by draycil** [peterhaneve/evemon#230]
I've added 6 characters to EveMon, and after an initial retrieval of the skill queue and other info, it will not update anymore. It simply attempts every minute or so, fails to retrieve, and starts another 1 minute countdown. The only way I can fix this is by deleting the character from EveMon and re-adding it. It will then update the latest skill queue and other info.

Any help would be appreciated.

**Comment by peterhaneve** [comment]
This issue appears to be ESI-related. If it still reproduces, consider sending the trace log file from `%APPDATA%\EVEMon\trace.txt`.
