### ISSUE TITLE
Some attribute names are invisible, but have tooltips

### ISSUE THREAD

**Issue by fonsuiplaysvideogames** [peterhaneve/evemon#232]
There are many item/ship attributes which display a blank name, but have a valid tooltip. Example:

![image](https://user-images.githubusercontent.com/60384561/82761787-12f21b80-9dcb-11ea-825a-51034b83dc5d.png)

**Comment by peterhaneve** [comment]
These fields appear to be missing short descriptions in the SDE. Unfortunately EVEMon can do nothing to add descriptions here, as the SDE is provided by CCP but has had spotty maintenance in the last few months.
