### ISSUE TITLE
Can this work on Mono on Linux?

### ISSUE THREAD

**Issue by saraaba** [peterhaneve/evemon#234]
Can this work on Mono on Linux?

No Wine, no VM, just Mono on Linux.

Packaged as an AppImage would be ok too.

**Comment by saraaba** [comment]
> Unfortunately Mono is missing some dependencies required to perform SSO authentication. A workaround is possible but would break on Windows, so both methods would need to be included.

Conditional compilation
Common abstraction
package as AppImage with all dependencies

**Comment by BanditSan** [comment]
@peterhaneve so why not just include not methods? Does including both break something else?
