### ISSUE TITLE
installer error

### ISSUE THREAD

**Issue by Gewinner2170** [peterhaneve/evemon#236]
I get the error message:  Extract: errror writing to file dropbox.Api.xml   in the setupmanager. I don't have the github app.

![EveMooninstallerror](https://user-images.githubusercontent.com/66794236/84416307-4ed31080-ac14-11ea-8964-c339978e70e4.JPG)

**Comment by peterhaneve** [comment]
It is likely that this issue is due to factors outside of EVEMon's control, including anti-virus software or lack of sufficient disk space. Have you tried another directory?

**Comment by Gewinner2170** [comment]
I have rather little workspace left on the windows disk, but I installed it to another harddrive. Installing it into another folder changed nothing. I had some struggles activating the .exe file in the first place, as it came from an unknowen source
