### ISSUE TITLE
Multiple Skills counting down

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#238]
Hi

Not sure if it's my fixes, but I have a training pilot with 5 new and unknown skill items in the queue and the remaining training time of all 5 of them is counting down. In the screenshot the top 5 items are counting down, from item 6 onwards the training time is fixed/not changing.

![image](https://user-images.githubusercontent.com/1768983/84595385-e96f6180-ae57-11ea-843a-c1e8eb029233.png)

**Comment by peterhaneve** [comment]
This is due to the skill items being unknown. A data update should resolve this issue, see #241.
