### ISSUE TITLE
Status bar display of single selected skill

### ISSUE THREAD

**Issue by NevarrTivianne** [peterhaneve/evemon#243]
Plan editor:

  * when no skill is selected, the status bar shows the total of skills planned + time + ISK + SP
  * when 1-n skills are selected, the status bar shows the total of selected skills planned + time + ISK + SP

Problem:

When only 1 skill level (one row) is selected, the status bar still shows the total. The workaround to find out the SP for a single skill level is to select 2+ skills, then ctrl-click to select the one you're actually interested in and doing the math in your head. Would be a lot easier if the single one would be shown when only 1 row is selected.

**Comment by peterhaneve** [comment]
This feature is already part of EVEMon, but is disabled by default. In Tools > Options > Skill Planner, deselect `Show Plan Summary Only On "Multi-Select"`.
