### ISSUE TITLE
Drone Interfacing IV marked as Alpha skill

### ISSUE THREAD

**Issue by Bonsailinse** [peterhaneve/evemon#248]
Just a minor thing, but the skill 'Drone Interfacing IV' is marked as trainable for Alpha characters, but it is only trainable on Omega.

![](https://cdn.discordapp.com/attachments/354368011945377794/750563806656200784/unknown.png)
![](https://cdn.discordapp.com/attachments/354368011945377794/750563620626235432/unknown.png)

Would be great if that gets fixed somewhen.
Have a nice day o/

**Comment by dresdor** [comment]
PR Created https://github.com/peterhaneve/evemon/pull/252

**Comment by peterhaneve** [comment]
Now updated, in a maintainable way, via commit 730cc41.
