### ISSUE TITLE
Expert Cerebral Accelerator causes remapping to bug out

### ISSUE THREAD

**Issue by mathieudevos** [peterhaneve/evemon#249]
Remapping calculator seems to not understand what the base values of a character are.
It views the current "base" values as the ones with the cerebral accelerator active, when you try to calculate a remap, it removes the bonus gained from the cerebral boost. 
This means that remapping always shows as being "slower" when you would remap for a certain plan. 

Fix would be to just do the count from the base, or have a checkbox for the "remain existing buffs & implants".

**Comment by Andf** [comment]
Something similar happens with the "masters-at-Arms" accelerator. 

Once the effects end, the active clone "remembers" the old bonus, even if it is not active anymore.

When tryin to optimize attribute, optimization says that it is worse than the current one.

**Comment by peterhaneve** [comment]
There is no ESI endpoint for active accelerators, so unfortunately there is no way to determine whether such an accelerator is active in the remap plan.

Upvote the https://github.com/esi/esi-issues/issues/783 on ESI Issues if you want to see this feature!
