### ISSUE TITLE
Machariel Not Showing Bonuses In Description Field

### ISSUE THREAD

**Issue by dresdor** [peterhaneve/evemon#251]
When viewing the Machariel, it is not showing anything for the Large Projectile Turret ROF

![image](https://user-images.githubusercontent.com/33524074/93838022-e2719f80-fc4d-11ea-9338-1b556b3a775f.png)

**Comment by peterhaneve** [comment]
It appears that the description of this field is missing in the CCP SDE, which is used by EVEMon to build the ship information screens.  Without manually editing the SDE it is unfortunately not possible to fix the change without a difficult to maintain whack-a-mole patch.
![image](https://user-images.githubusercontent.com/29011570/94189060-18d23900-fe5f-11ea-9dde-c4b73f90d0c7.png)
