### ISSUE TITLE
ESI token could not be obtained.

### ISSUE THREAD

**Issue by Kenbric** [peterhaneve/evemon#254]
Started with Evemon reporting none of my character profiles having esi tokens attached to them. I attempted to update, then delete and create new ones and receive an error on the last step of importing a character that has remained persistent over the course of a couple days, pc restarts, pausing anti-virus protection, running as admin and Evemon reinstalls. This issue is occurring on a pc running Win7.

![image](https://user-images.githubusercontent.com/72276852/94959027-7d744000-04be-11eb-9740-030230ca5926.png)

This happens even though login to eve online sso works and my web browser returns with "AUTHENTICATION SUCCESSFUL"

I have been unsuccessful in recreating this issue (it adds the character as intended) on another computer running Win10 and on the same same network.

This is a copy paste from the trace.txt that I hope can help explain where the problem is occurring.

> 0d 0h 00m 26s > ExceptionHandler.LogException - Handled exception
>     EVEMon.Common.Net.HttpWebClientServiceException: A request to login.eveonline.com failed with status: ReceiveFailure. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.IO.IOException: The decryption operation failed, see inner exception. ---> System.ComponentModel.Win32Exception: The token supplied to the function is invalid
>    --- End of inner exception stack trace ---
>    at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
>    at System.Net.TlsStream.EndRead(IAsyncResult asyncResult)
>    at System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
>    --- End of inner exception stack trace ---
>    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
>    at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
>    --- End of inner exception stack trace ---
>    at EVEMon.Common.Net.HttpClientServiceRequest.<SendAsync>d__8.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at EVEMon.Common.Net.HttpWebClientService.<DownloadStringAsync>d__2.MoveNext()

I've searched online for similar issues, causes and fixes to them, but this issue seems to be local and unique to my computer.

**Comment by peterhaneve** [comment]
This issue appears to be [SSL certificate or configuration related](https://stackoverflow.com/questions/40939031/tls-1-2-the-token-supplied-to-the-function-is-invalid). Try enabling the latest SSL algorithms in Internet Options, and make sure that the computer's SSL certificate cache is up to date.
