### ISSUE TITLE
Updated data files won't download

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#257]
Updated data files won't download

**Comment by Ninnikuu** [comment]
Same here

**Comment by ezi0o** [comment]
same here :-/

**Comment by dCosminn** [comment]
same here

**Comment by csatlos** [comment]
I believe it's an issue with the download URL for the update files in [patch.xml](https://github.com/peterhaneve/evemon/blob/fcd11c057d942031b3524048eaa98e37870f268d/tools/PatchXmlCreator/Output/patch.xml).

I think "<url>https://peterhaneve.github.io/evemon-datafiles/Invasion/1.11</url>" should read, "<url>https://peterhaneve.github.io/evemon-datafiles/Invasion/1823246</url>"

**Comment by Local9** [comment]
Those having the issue, current work around is on the forums; 

https://forums.eveonline.com/t/evemon-4-0-18-esi-edition/75953/476
