### ISSUE TITLE
First Load Is Slow & Janky With Window Visible

### ISSUE THREAD

**Issue by IcyMidnight** [peterhaneve/evemon#258]
I have 44 characters in EveMon (and I'd like to add more). The initial load takes a long time (> 1 minute) and the entire interface is locked up for 99% of that time. It appears as if the entire application redraws after each character loads (window blanks and UI elements flow back onto the screen). If I repeatedly click on the minimize button until I catch a short period where the UI is responsive, the window minimizes and the app finished loading almost immediately thereafter (i.e. I can bring the window back up ASAP and the app is done loading).

As a work around, it would be nice for the app to start minimized.

**Comment by IcyMidnight** [comment]
I realized that I made an error in describing the problem. The app does start out minimized, but the first time I show the window, it does some sort of heavy refresh that takes a really long time unless I minimize and then bring the window back.

**Comment by peterhaneve** [comment]
EVEMon's current architecture will always be slow with 44 characters, as it creates the controls in all tabs when the program is loaded. Improving performance will likely require a near-total rewrite of EVEMon.

**Comment by IcyMidnight** [comment]
Like I said, you can work around this by opening the main window, minimizing it as soon as possible, and then bringing the window back to life. Whatever is happening during that time takes 1-2 minutes with the window up or < 1s with the window minimized. Hopefully a full re-architecture is not required to emulate the window being minimized. Maybe whatever process occurs during the first window bring-up could be triggered before the window spawns for the first time, or the UI drawing could be turned off for the first refresh or something?

**Comment by IcyMidnight** [comment]
FWIW someone has fixed something since I posted this and this is worlds better! Thanks someone!
