### ISSUE TITLE
logitech keyboard G13/G15/G510 no longer woking 

### ISSUE THREAD

**Issue by Solarwuff** [peterhaneve/evemon#259]
Today after a fresh reinstall of evemon i found out the the logitech keyboard applet no longer is loading / installing 
I did dubble check if i have the last version of both evemon and the logitech gaming software and both are fully up to date

**Comment by eldarmark** [comment]
The latest update removed Logitech keyboard applet suport, sadly.

**Comment by Solarwuff** [comment]
well thats very sad new to hear

I presume that there is no way to add this function back manually ?


Also if the support is fully removed then i would recommend to removed the option for it in the settings menu 
as of from the last update it's still there 

<img width="483" alt="evemon" src="https://user-images.githubusercontent.com/49283198/96365287-d4754880-113f-11eb-9781-b05fe72d63c1.PNG">

**Comment by peterhaneve** [comment]
Issue #246 was requested to remove this keyboard support, claiming that it is unavailable and broken. Did it actually still work?

**Comment by Solarwuff** [comment]
as of like to updates back it did still worked for me 04/15/2020 

![](https://cdn.discordapp.com/attachments/403250349059604481/700071611411333300/20200415_215357.jpg)
