### ISSUE TITLE
Mac Version

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [peterhaneve/evemon#260]
According to Eve Uni, EveMon is available for Mac.  Is there a separate link for this?

Thanks for continuing this project!  I used to use it on Windows but I'm on Mac now.  Cheers!

**Comment by peterhaneve** [comment]
There is no separate Mac version. You could try running it on Mono, but there are a few missing Windows dependencies. However, authenticating your characters on Windows and copying the settings XML file will allow EVEMon to be used normally on Mac. See issue #97.
