### ISSUE TITLE
Feature Request: Players can add, remove and reorder skills on their character skill queue

### ISSUE THREAD

**Issue by strich** [peterhaneve/evemon#261]
EVEMon is a great tool for managing skill plans however it would be greatly strengthened if we could perform actions on the skill queue from the app so we don't have to go in-game to make changes. This can be specially important when using multiple accounts.

I believe ESI allows this as the official EVE Portal mobile app can do these actions.

**Comment by peterhaneve** [comment]
Unfortunately there is no ESI endpoint for modifying skill queues:
![image](https://user-images.githubusercontent.com/29011570/98426016-27aa2f00-204c-11eb-811e-882d972653d2.png)
Open an issue on https://github.com/esi/esi-issues/issues if you want to see this feature!
