### ISSUE TITLE
Feature Request: Pull Skill Injector Cost Data

### ISSUE THREAD

**Issue by CookieWookiee** [peterhaneve/evemon#262]
For spooling up alts using skill plans you've created, I would find it valuable to see the Jita price of the total number of skill injectors needed without needing to check it in game/a spreadsheet. The actual implementation doesn't matter, but my recommendation would be including it to the right of the injector quantity readout.

**Comment by peterhaneve** [comment]
Skill injector prices have been added to the **tool tip** of the injector quantity in 10aaef3.
