### ISSUE TITLE
Logitech LCD layout error

### ISSUE THREAD

**Issue by Solarwuff** [peterhaneve/evemon#263]
I am not sure if this is a problem with evemon or the Logitech api 
But it looks like that long names are getting compressed as seen in the photo 

![photo_2020-11-08_21-27-06](https://user-images.githubusercontent.com/49283198/98483496-2e31d580-2209-11eb-8dc3-63523868f22f.jpg)

**Comment by peterhaneve** [comment]
Unfortunately EVEMon has no control over exact text rendering, as it just draws the string directly using system API calls: https://github.com/peterhaneve/evemon/blob/main/src/EVEMon.LogitechG15/LcdLine.cs#L66
