### ISSUE TITLE
Feature request: Pre defined implant sets

### ISSUE THREAD

**Issue by 12gabriel3** [peterhaneve/evemon#265]
Currently, the only predefined implant sets are the ones from our clones. If I want to see how much time I would gain from going from a +4 to a +5 implant set I have to manually create an implant set and choose the right implants among the infinite irrelevant options that have no influence over skill training.
It would be nice to have the +1, +2, +3, +4 and +5 presets show up along your clones in the dropdown menu like the picture below.
![image](https://user-images.githubusercontent.com/16885097/100191191-7c63fb80-2ece-11eb-8cf9-f713af632478.png)

**Comment by peterhaneve** [comment]
Implant sets in EVEMon must have a unique name. If users have already created a set with a name like `+3` (possibly with other custom implants), and EVEMon adds a new predefined set named `+3`, it may clobber user preferences. As the implant set can be created once per character and used indefinitely, the risk of adding this change likely outweighs the potential benefit.

**Comment by 12gabriel3** [comment]
It could be an option when you create an implant set. When you select a predefined set it selects the corresponding drop down menus for each slot
![EVEMon_suggestion](https://user-images.githubusercontent.com/16885097/112765617-52d5f080-8fe4-11eb-8f52-7cf21dc76f38.png)
