### ISSUE TITLE
Salvage Drone Specialization Issues

### ISSUE THREAD

**Issue by doomlord289** [peterhaneve/evemon#270]
It looks like there's a number of issues with the Salvage Drone Specialization skill.

- Prerequisites are missing (Salvage Drone Operation V and Salvaging IV)
- Evemon has it a 1x  training time multiplier, but in-game it's a 5x multiplier
- As mentioned in issue #268, the training time isn't calculated at all (it's 999d for each level)

**Comment by wvdvegt** [comment]
Debugging a bit points to BaseCharacter.cs GetOmegaSPPerHour() method where both PrimaryAttribute and SecondaryAttribute are None, resulting in the method to return 0 which ruins the calculations.

**Comment by wvdvegt** [comment]
The static data is also missing the attributes (which is probably the origin):

```
    <skill public="true" id="57164" name="Salvage Drone Specialization" description="" primaryAttr="none" secondaryAttr="none" rank="1" cost="0">
      <AlphaLimit>0</AlphaLimit>
    </skill>
```

**Comment by wvdvegt** [comment]
Adding the attributes to the eve-skills-en-US.xml file 👍 

    <skill public="true" id="57164" name="Salvage Drone Specialization" description="Advanced proficiency at controlling salvage drones. 2% bonus to the max velocity and salvage chance of drones requiring Salvage Drone Specialization per level." primaryAttr="memory" secondaryAttr="perception" rank="1" cost="0">
      <AlphaLimit>0</AlphaLimit>
    </skill>

already fixes a lot. 
1) In the queue the remaining training time is still off and the SP: value in queue items is still off/wrong. 
2) Strangely in the skill browser it shows a correct value for training behind level V where the queue trains to IV (so the nextSP values seem to be one level off).

Note the other tags (prereqs are still missing).

**Comment by wvdvegt** [comment]
Issue is fixed in the latest static data (which introduces two new similar issues for the new fleet formation skills).

**Comment by peterhaneve** [comment]
The latest SDE update now has values for the skills.
