### ISSUE TITLE
Feature request: show progress of PI extractors(like a percentage)

### ISSUE THREAD

**Issue by Sidius-DEV** [peterhaneve/evemon#272]
I used to have a website that showed the progress of extractor programs on planets. I can not find anyplace else which does this now that I do not have access to that site anymore. would be a nice addition to the app.

**Comment by peterhaneve** [comment]
This feature is impossible to implement, because as the [ESI documentation](https://esi.evetech.net/ui/#/Planetary%20Interaction/get_characters_character_id_planets_planet_id) states:
> Planetary information is only recalculated when the colony is viewed through the client. Information will not update until this criteria is met.
