### ISSUE TITLE
The new Fleet (formation) related skills are missing.

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#274]
The new skills for unlocking fleet formations are missing in the dataset.

**Comment by gokeefe** [comment]
The new Mobile Cynosural Beacon item and blueprint is also missing. Was trying to figure out why EVEMon wasn't displaying the running industry jobs for researching them. I'm guessing that's why? If not, I can create another issue for it.

**Comment by peterhaneve** [comment]
The most recent static data update released two days ago is broken - the attributes are all missing for the Fleet skills, and the cynosural beacon has an invalid Market Group ID. I can manually hack the beacon, but until the SDE is fixed the fleet skills will not work properly.
