### ISSUE TITLE
New Fleet Skills Missing Info

### ISSUE THREAD

**Issue by doomlord289** [peterhaneve/evemon#276]
I downloaded the new data files from commit 10aaef3faed3cbb0bb5c884d2ac51295185f6b3c to add the new Fleet Formations and Fleet Coordination skills to my plan, but noticed they don't have their prerequisites, multiplies, attributes, or descriptions loaded (similar as to what happened with the Salvage Drone Specialization skill that I mentioned in issue #270).

Is this another issue with the SDE?

**Comment by doomlord289** [comment]
I manually went into game and copied the relevant data for the 2 new skills (Fleet Formations and Fleet Coordination) into the XML file.

If anyone wants to manually update their XML, here's the updates:
```xml
    <skill public="true" id="57318" name="Fleet Coordination" description="Advanced fleet support skill allowing commanders to increase the size and spread of their fleet formations. Unlocks additional formation scaling options at each level of training." primaryAttr="charisma" secondaryAttr="willpower" rank="8" cost="40000000">
      <prereq id="3348" name="Leadership" level="5" />
      <prereq id="57317" name="Fleet Formations" level="1" />
      <AlphaLimit>0</AlphaLimit>
    </skill>
    <skill public="true" id="57317" name="Fleet Formations" description="Fleet support skill allowing commanders to organize and warp fleets in formation. Unlocks additional formation types at each level of training." primaryAttr="charisma" secondaryAttr="willpower" rank="5" cost="40000000">
      <prereq id="3348" name="Leadership" level="5" />
      <AlphaLimit>0</AlphaLimit>
    </skill>
```

The file you need to update is: %appdata%\EVEMon\eve-skills-en-US.xml.gzip

You'll need to extract the XML contained in the gzip file, find the existing data (the IDs and names are there), then overwrite those 2 blocks with the XML above, save the XML, then copy the XML back into the gzip file.

**Comment by peterhaneve** [comment]
While this could be hacked manually in the XMLs, it would be overwritten on each new release unless CCP fixes the skills. But since ESI and the SDE are essentially no longer maintained, my hopes are not high for a fix upstream. Therefore I have hardcoded the fixes, along with a growing list of other workarounds, into the XML Generator.
