### ISSUE TITLE
Feature Request: Allow me to list the Starter Skills in a new skill plan.

### ISSUE THREAD

**Issue by poundjd** [peterhaneve/evemon#279]
When building a new skill plan It would be Awsome to have the starter skills listed in the same section just above the items' I am adding, thus avoiding looking to the far right of the (Think Wide Monitors) monitor.  This has caused me no end of consternation on many occasions when hand-inputting lower-level skills.

**Comment by peterhaneve** [comment]
Consider creating a blank character of the desired race with the Blank Character Creator in Tools. This character will have all of their skills set to the starting values.
![image](https://user-images.githubusercontent.com/29011570/118903831-66f3eb00-b8cd-11eb-815b-1c06afb22ffa.png)
