### ISSUE TITLE
implant +5 Attribute adjustment not possible

### ISSUE THREAD

**Issue by poundjd** [peterhaneve/evemon#282]
Need to be able to insert into skill plan a new (or first) set of implants, and then need to be able to adjust the resulting attributes.

**Comment by peterhaneve** [comment]
Custom Implant Sets can already be defined in the Tools menu under Implant Groups.
![image](https://user-images.githubusercontent.com/29011570/118903194-1203a500-b8cc-11eb-8bc5-620e30da0e08.png)
