### ISSUE TITLE
the attributes are in the wrong order

### ISSUE THREAD

**Issue by sportshead** [peterhaneve/evemon#289]
evemon gives attributes in the order intelligence, perception,  charisma, willpower, then memory.
eve online gives attributes in the order perception, memory, willpower, intelligence, then charisma.
I think you can see where this is going. I put in the attributes in the order that evemon gave me thinking it would be the same in the game. Needless to say, it was not, and I wasted my neural remap. Please fix this ASAP

**Comment by peterhaneve** [comment]
The order given by the EVE client's attributes has not been consistent over time, and even with itself:
https://tagn.files.wordpress.com/2017/10/remapattibutesinremapper.png
http://crossingzebras.com/wp-content/uploads/2015/02/Neville-character-sheet.jpg
https://tagn.files.wordpress.com/2017/10/remapattibutesinremapper.png

Changing this order might throw off as many people as it helps.
