### ISSUE TITLE
evemon not ready for new ESI rollout

### ISSUE THREAD

**Issue by jamiew0w** [peterhaneve/evemon#306]
Hello guys and girls.

I presume people are already aware of this but i'm making an issue just in case. Evemon hasn't been working (for me and some alliance mates) for the last few days so I assume it's due to the ESI changes CCP rolled out recently.

[Here's their forum thread announcing the changes](https://forums.eveonline.com/t/information-on-changes-to-esi-for-third-party-applications/334081)

**Comment by gokeefe** [comment]
Fix is already documented [here](https://github.com/peterhaneve/evemon/issues/300). Can't count on a new official build becoming available anytime soon though so you'll have to implement the patch and rebuild yourself, or find a trusted source to do so for you. (There is a build available in r/eve but YMMV.)

**Comment by jamiew0w** [comment]
> 
> 
> Fix is already documented [here](https://github.com/peterhaneve/evemon/issues/300). Can't count on a new official build becoming available anytime soon though so you'll have to implement the patch and rebuild yourself, or find a trusted source to do so for you. (There is a build available in r/eve but YMMV.)

Thanks @gokeefe !

I'd like to wait for an official build, is there an approximate time? For example, a few days or a month - just so I know where to set expectations. Thanks again!

**Comment by gokeefe** [comment]
I'm not a contributor so I can't say, but the project owner hasn't pushed a new commit in 8 months so I wouldn't assume a new official build is going to be coming anytime soon, maybe never? The build instructions are fairly easy though (even I was able to figure it out) so that might be your best option.

**Comment by CodesignDev** [comment]
I'm currently working on updating evemon over in a fork of mine. I've already fixed the ESI Character endpoint and I've just pushed a fix to fully move over to SSO V2.

I haven't got builds just yet, but I'm currently working on getting the updated data files sorted.

My repo is over at https://github.com/evemon-app/evemon

**Comment by jamiew0w** [comment]
@peterhaneve should we consider this repo inactive/abandoned?

**Comment by bbsixzz** [comment]
@peterhaneve can you please reply?

I love this tool, I only wish I could help fix it.

**Comment by Marius8** [comment]
@peterhaneve updated another repo recently..
please respond soon

**Comment by jamiew0w** [comment]
@Marius8 @bbsixzz there's a maintained fork here (https://github.com/mgoeppner/evemon), it's updated to work with new ESI endpoints. peter doesn't seem interested so i'm closing this issue
