### ISSUE TITLE
EVEMon freezes when opening skill plans

### ISSUE THREAD

**Issue by zrupcic** [peterhaneve/evemon#321]
For the past few weeks, if I open a skill plan or try to switch between skill plans, EVEMon freezes and I have to close the application (EVEMon doesn't respond but the X button still works so I'm not required to use the task manager). 
This doesn't happen outside of visiting skill plans, so I suppose the issue is related with the skill plan window. It is also happening on different computers. Of course since there have been no recent updates to EVEMon I have no idea what might cause this.

**Comment by michaelmdresser** [comment]
Check out https://github.com/mgoeppner/evemon/issues/63

**Comment by zrupcic** [comment]
Thanks! I didn't notice that I'm on the wrong repository. Clearing the cache fixed the issue.
