### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by kinstalinist** [peterhaneve/evemon#35]
Even with the fix in my pull request (#34), building still fails on Linux. I'm not sure how to fix this one myself though.

I've attached the full log from one of my attempts to build the project, but for reference here's the significant part:

```
Errors:

/home/kinsey/git/evemon/EVEMon.sln (default targets) ->
(Build target) ->
/home/kinsey/git/evemon/src/EVEMon.Common/EVEMon.Common.csproj (default targets) ->

	: error : Target 'ResolveKeySource', a dependency of target 'GenerateSerializationAssembliesForAllTypes', not found.
```

[msbuild.log](https://github.com/peterhaneve/evemon/files/2136016/msbuild.log)

**Comment by peterhaneve** [comment]
While debug builds on Linux might be possible, I believe that building the installer might pose a whole new set of issues. Which distribution were you trying to use?

**Comment by kinstalinist** [comment]
Heh, yeah. I'm using Arch. After tinkering with it some more I've kinda realized I probably bit off more than I can chew with trying to make this work on Linux. I think I might have more luck reworking [GtkEveMon](https://github.com/gtkevemon/gtkevemon) to use ESI.

**Comment by peterhaneve** [comment]
While I do not oppose trying to get EVEMon to work on Linux, my expertise on building C# projects there is quite fuzzy. Does EVEMon fail when wine/mono is used?

**Comment by peterhaneve** [comment]
Feel free to keep discussing this issue, but I believe that I do not have the setup required to attempt to build EVEMon on Linux. I will close the issue for now and perhaps investigate it later.
