### ISSUE TITLE
One application scope set

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#38]
The idea behind the oauth2 scopes necessary for Eve ESI access is that the developer supplies a set (and had a clientID in the application). So NOT every user creating a personal application & scope set but the developer defining a set that is the maximum that the application needs when all features are enabled.

The app (like Evemon) should ideally be able to work with subsets of the full scope (so for instance a client app not requesting corporate scopes).

So in Evemon when logging into eve for authorization one should request a set of scopes chosen by the user for a particular pilot. Basically one could check the scope(s) of each tab one uses or has enabled and combine those into the login request.

**Comment by wbSD** [comment]
#13 allows for configuring which scopes you decide to grant access to when adding an ESI key.
If you scroll down through the conversation, I uploaded some pictures of how it looks when you choose what to request.

What it doesn't do is change the fact that each individual user will need to create their own ESI application key on developers.eveonline.com

**Comment by wvdvegt** [comment]
> What it doesn't do is change the fact that each individual user will need to create their own ESI application key on developers.eveonline.com

This is exactly what should have been repaired as well. Otherwise we see an explosion of applications at CCP and id something changes, all users have to alter their app as well. The idea is the programmer decides the max need set and the user decides if he want to give/grant it.

**Comment by wbSD** [comment]
The problem is that EVEMon is a stand-alone desktop application. There's no existing service where the developer application can be hosted.
And setting that up will mean adding extra work maintaining and securing it.
There's actually a lot of discussion about just that on the ESI EVEMon forum thread, here are a few example replies on the thread.
https://forums.eveonline.com/t/evemon-4-0-3-beta-esi-edition/75953/33
https://forums.eveonline.com/t/evemon-4-0-3-beta-esi-edition/75953/123

**Comment by wvdvegt** [comment]
Think you get things wrong. ESI oAuth2 is ment for desktop apps as well. It's the opposite as the old crest systems where you defined what apps may see. There you defined what apps using a key could see. You could enable all and only use little. Main issue with desktop apps is the browser needed to login.

Now you define what an application can see max and there is no way you can get more or can deviate except ask for less (so for instance ommit corp scopes). There is not need for hosting or creating a service etc. You just share your app clientID.

Only issue is the inclusion of a clientID (not a problem) but especially the Client Secret. You need to pass the latter during login. But even if they leak it's probably not worse as you can (as an app) never get more then defined as ESI application. If you submit less scopes you get less access. If you supply (as a game) more scopes you get an error that the scopes are not valid. You should not commit the client secret to GitHub i think. But you can include it (using secure strings or other methods) in a compiled app.

I can share my desktop UWP app with you and you would only have to login (be presented the app scope set I defined) and agree to what my app asks for. My app does not handle subsets (yet) so not agree = not use my UWP app. 

What's different with ESI SSO for everybody is that they have to login with eve credentials to be able to agree on the requested scopes. Previously you could save the xml API keys in a text file and use them in all kind of apps without logging in again. That no longer works.

Above is how i think it works.

**Comment by wvdvegt** [comment]
https://tools.ietf.org/html/rfc6819#section-4.1.1 maybe usefull (about secret risks)
https://developers.google.com/identity/protocols/OAuth2UserAgent (contains examples of desktop app calls with secrets)
