### ISSUE TITLE
Alpha

### ISSUE THREAD

**Issue by IntelOut** [peterhaneve/evemon#43]
It would be nice if skills have description - that certain level of skill can't be trained at alpha accounts.
and if char has alpha status it can't be added to skill plan.
Just a proposal.

**Comment by peterhaneve** [comment]
I did not find a location for this information in the current CCP Static Data Export (SDE). Do you know where a list of the allowable alpha skill levels are found?

**Comment by IntelOut** [comment]
Made a list.
[alphaskills.txt](https://github.com/peterhaneve/evemon/files/2152593/alphaskills.txt)

**Comment by peterhaneve** [comment]
If a feature like this were to be added to EVEMon, the objective would be to ensure that the alpha trained skills could be kept up to date without manual editing. While I understand (and would like to see this feature too), I would prefer to only implement this feature if there was a fully updated CCP source for this information.

**Comment by IntelOut** [comment]
I see. Made a petition to CCP, waiting for response. :)

**Comment by IntelOut** [comment]
Got a response. "Their ESI support is limited. RTFM..." :(
Just found such method. May be it could work.
https://github.com/esi/esi-issues/issues/133#issuecomment-305005486

**Comment by peterhaneve** [comment]
If ESI or the static data ever exposes this information, this feature can be added, but for now this issue cannot be realistically fixed.
