### ISSUE TITLE
Feature Request: Ability to put a label on a character / Group characters

### ISSUE THREAD

**Issue by Krisscut** [peterhaneve/evemon#44]
Hi, 

First, thank you to have port this awesome app to the ESI ! 🥇 

I think it would be nice to have the ability to put a **"label"** on an alt, which can then be displayed on the overview Page if the label is set (ie not null).

Some usecases like putting the accout name/role of the alt comes to my mind to justify that request. (no more logging on a account to notice that it's the wrong one, or the wrong char for the job !

It would also be nice to be able to group some characters together in the overview using a label (again, to quickly find char on the same account)

**Comment by peterhaneve** [comment]
Adding a label to each character would not be overly difficult, but visually grouping by it on the overview would be more challenging. Would sorting by label work instead?

**Comment by Krisscut** [comment]
Yeah sorting alphabetically by label would be perfect. (at least in my usecase)
But the sorting is just a nice to have, the label is the main focus of this request. :smile:

I don't know if other people find that idea interesting, you may have higher priorities than doing that.

**Comment by Krisscut** [comment]
Yeah i did discovered that feature the other day accidentally 

Thanks for the implementation of the labels, it's gonna be super helpful !
