### ISSUE TITLE
Assets Price not updateing 

### ISSUE THREAD

**Issue by DTBA** [peterhaneve/evemon#46]
Any Idea why it is not updating the prices from eve market ?

Or should I just leave it and it will update it over time?

![capture](https://user-images.githubusercontent.com/15993596/42211319-988f25d2-7eb3-11e8-910c-30b7a47b8100.JPG)

**Comment by peterhaneve** [comment]
If you have thousands of entries in the assets window, it may take several minutes to obtain the price for all of them. The next version of EVEMon will enable EVE Marketer as another source for market prices in case EVE MarketData does not work.
