### ISSUE TITLE
Completed industry job items count to high.

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#47]
In the latest version 4.0.5.4828 i frequently see notification with two or more times the number of completed industry jobs. Seems numbers keep accumulating. 

The notification details also shows duplicate entries.

**Comment by wvdvegt** [comment]
Seems to happen when you leave Evemon running and do not dismiss the notification bars above the listviews.

**Comment by peterhaneve** [comment]
It looks like (at least for industry jobs) this was due to a typo. Are you able to try out the most recent debug version and see if they go away?

**Comment by wvdvegt** [comment]
I'll try.

**Comment by wvdvegt** [comment]
Issue is still there but the asset related commit on top also gives huge problems.

**Comment by wvdvegt** [comment]
I reset the code to your notification patch and my inaccessible structure fix (needed that last one). Still the finished job count is off.

![capture](https://user-images.githubusercontent.com/1768983/42311530-5b832616-803e-11e8-8362-fc6ec92f7860.JPG)

**Comment by peterhaneve** [comment]
I think that this was fixed by fixing the previously mentioned typo. It would take one restart cycle to clear the invalid jobs.
