### ISSUE TITLE
Warning: 199 - This route has an upgrade available.

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#50]
The endpoint:

`https://esi.evetech.net/v1/universe/structures/<id>/`

gives a warning 'Warning: 199 - This route has an upgrade available.'

**Comment by wvdvegt** [comment]
Had a look at the swagger site and the upgrade seems to be a /dev/ version. So better wait until it's out of dev i guess unless it solves something.

**Comment by peterhaneve** [comment]
Yeah I am not going to update the route until it hits latest and gets a version number. Actually, I noticed this already and added the new fields as optional to the structure class. Once it goes live I will add the version number and copy the new field to the EVEMon structure class.

I am also considering adding a popup in debug editions if ESI returns an indication of outdated endpoint, but not sure if this actually would trigger early enough to be useful.
