### ISSUE TITLE
Move some non settings out of settings.xml

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#52]
settings.xml seems polluted a bit by entries that are not settings but pilot related data. 

The <skills> tag is a fine example. This belongs in a separate file in a pilots' cache i.m.h.o.

Same for <implants>, <queue> <marketOrders> <contracts> <eveMailMessages> <eveNotifications> and <industryJobs> (and maybe even more).

**Comment by peterhaneve** [comment]
Unless this is impacting EVEMon functionality in some way, it is probably better not to change this due to the settings migration impact, particularly on users with dozens of characters.

**Comment by wvdvegt** [comment]
Agree, but plz keep it in mind for a future release. This kind of data should be cached so re-downloadable anyway.
