### ISSUE TITLE
Notification Tray popop just appears randomly - what do fc??

### ISSUE THREAD

**Issue by mikeyhalla** [peterhaneve/evemon#58]
I'm more interested in being able to shut off the popup from the notification icon that shows my characters but the actual issue at hand is that it will appear out of nowhere at times. Just randomly appears where my cursor is even though it's nowhere near the icon in the notification tray.

Again, an option to actually shut that off would be great. I don't need to see that popup ever.

Thank you for your hard work!

**Comment by mikeyhalla** [comment]
I just found the option to shut it off but the actual issue is still there unless you do shut it off but as far as I'm concerned, problem solved.

Thanks for getting to me on this issue. Just like an Eve player to ignore this. LOL

Fly safe!

**Comment by peterhaneve** [comment]
Sorry that I did not get to look at this sooner, was not able to work on EVEMon for a while due to RL issues. I have never had this issue repro. Does this mean that the system tray right-click popup appears when you do not click on the icon?
