### ISSUE TITLE
Assets not available?

### ISSUE THREAD

**Issue by Fire1nRain** [peterhaneve/evemon#59]
New to this tool and new to EVE.
When I'm checking assets, it always displays a "No assets are available" message.
Is this normal?

**Comment by peterhaneve** [comment]
Do the other EVEMon functions work properly? One frequent cause of some tabs failing is an incomplete scope list, make sure that you followed the instructions in https://peterhaneve.github.io/evemon-esi carefully.

**Comment by Fire1nRain** [comment]
@peterhaneve most of them works fine for most of the times
However, sometimes one or more of the tabs failed to get the data and there seems to be no way of refreshing these unavailable ones manually, 
As for assets, I never saw it working properly.
I've checked the scope and actually I simply added all of them
