### ISSUE TITLE
Feature Request: Dark Theme.

### ISSUE THREAD

**Issue by esheyw** [peterhaneve/evemon#61]
Please. My eyes.

**Comment by peterhaneve** [comment]
While I thought this would be a huge rewrite at first, the resources at https://psycodedeveloper.wordpress.com/2013/01/18/implementing-your-own-colour-themes-in-a-c-windows-forms-application/ show that this may be easier than I first estimated. However, recoloring the EVEMon image assets would be challenging, especially the files pulled from CCP image dumps that may not have a dark version.

**Comment by peterhaneve** [comment]
I gave the dark theme a shot, but many of the icons (particularly the toolbar) do not fit with a dark theme or are unreadable. If you have a suggestion for a good alternative icon set, let me know and I can look at this issue again.
