### ISSUE TITLE
Update the Help Menu

### ISSUE THREAD

**Issue by gavello** [peterhaneve/evemon#63]
Currently the help menu points towards the old development team and old eve forum link. Would be nice for this to be updated to this fork when using this version so its a handy way to check for updates.

Minor fix, but quality of life change none the less.

**Comment by peterhaneve** [comment]
Mirroring the entire former EVEMon site (http://evemondevteam.github.io/evemon) will be challenging. Despite the fact that it is somewhat out of date, it has quite a bit of good information.

The eve forum link in the Help menu points to the correct page. The outdated Twitter link has now been removed and the Suggest a Feature button redirected to this GitHub.
