### ISSUE TITLE
SkillBrowserControl.UpdateOwnedSkillBookControls()

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#69]
While clicking around in the Skill Browser/Explorer back and forth i got a `NullReferenceException `in `UpdateOwnedSkillBookControls()` on:
```
OwnedSkillBooksWindow ownedSkillBooksWindow =
  WindowsFactory.GetByTag<OwnedSkillBooksWindow, Character>((Character)m_plan.Character);
```
where `m_plan` was null.

**Comment by wvdvegt** [comment]
Seems to happen if you right click a skill you don't own in the Skill browser.

**Comment by peterhaneve** [comment]
I cannot seem to repro this one but added a null check anyways in 50822b0c to make sure.
