### ISSUE TITLE
Bill issues amounts are sometines x10 off

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#73]
Message in Eve:

> This is an automatic message. A bill of 1.200.000,00 ISK, due Tuesday, September 18, 2018 owed by you to UNITED SOCIETY GAMING COMMUNITY was issued Sunday, August 19, 2018. This bill is for extending the lease on your Office at Yulai - USGC Public Industry.

Evemon's message:

> This is an automatic message. A bill of 12.000.000,00 ISK, due Tuesday, September 18, 2018 (EVE Time) owed by you to UNITED SOCIETY GAMING COMMUNITY was issued . This bill is for extending the lease on your Office at Yulai - USGC Public Industry.

It seems to happen for amounts over 1M ISK only.

**Comment by wvdvegt** [comment]
Cause is simple, outside the US the decimal separator can differ. The input is 120000.0 which without further code is parsed into 12.000.000.

The lines (in \src\EVEMon.Common\Models\Extended\InternalEveNotificationTextParser.cs)
```
  case "ISKVALUE":
                // Format as ISK amount
                if (decimal.TryParse(value, out amount))
                    parsedDict[key] = amount.ToString("N2");
                break;
```

should read:
```
  case "ISKVALUE":
                // Format as ISK amount
                if (decimal.TryParse(value,NumberStyles.Number, CultureInfo.InvariantCulture, out amount))
                    parsedDict[key] = amount.ToString("N2");
                break;
```

This localization error may be present on more places.

**Comment by peterhaneve** [comment]
After auditing the code I fixed around 10 other instances where invariant culture should have been used.
