### ISSUE TITLE
Update Account info when you change passwords

### ISSUE THREAD

**Issue by mikeyhalla** [peterhaneve/evemon#75]
I updated my passwords on my account in eve online and when I was fixing the sync error in evemon, it only shows numbers instead of character names which makes it very difficult to tell which belongs to which.

Reproduce by changing your password for your eve accounts.

**Comment by peterhaneve** [comment]
Changing your password will always require you to log in to EVEMon again. There is nothing that EVEMon can do to affect this.

However, the diagnostic message can be improved somewhat. See 47df1a2.
