### ISSUE TITLE
Ship browser does not distinguish between Tech 1 and Tech 2 ship bonuses.

### ISSUE THREAD

**Issue by lps1975** [peterhaneve/evemon#76]
For most of it's life, the EveMon ship browser would distinguish the difference between a ship's basic skill bonuses and the "advanced" bonuses (for lack of a better term) for the Tech 2 aspects of the ship.

For example, before this bug, the Golem (Caldari battleship) would be described as follows. (Important note: there are three skill categories, indicated with ---

```
--- Caldari Battleship bonuses (per skill level): ---
10% bonus to Cruise Missile and Torpedo max velocity
5% bonus to Cruise Missile and Torpedo explosion velocity
--- Marauders bonuses (per skill level): ---
7.5% bonus to Shield Booster amount
10% bonus to Target Painter effectiveness
--- Role Bonus: ---
100% bonus to Heavy Missile, Cruise Missile and Torpedo damage
100% bonus to Tractor Beam range and velocity
70% reduction in Micro Jump Drive reactivation delay
• Can fit Bastion modules
```

Unfortunately, at some point in the recent past, EveMon now collapses the first two categories together. It is now more difficult to understand what bonuses come from where:

```
--- Traits --- 
Golem bonuses (per skill level):
10% bonus to Cruise Missile and Torpedo max velocity
5% bonus to Cruise Missile and Torpedo explosion velocity
7.5% bonus to Shield Booster amount
10% bonus to Target Painter effectiveness

Role bonus:
100% bonus to Heavy Missile, Cruise Missile and Torpedo damage
100% bonus to Tractor Beam range and velocity
70% reduction in Micro Jump Drive reactivation delay
Can fit Bastion modules
```

**Comment by peterhaneve** [comment]
This bug existed from before the ESI conversion according to https://github.com/evemondevteam/evemon/issues/88

**Comment by lps1975** [comment]
So am I to understand that you are not necessarily taking over the maintenance and development of EveMon, correct? You are only doing an ESI fork that you hope gets merged back into the main development effort?
