### ISSUE TITLE
Market buy orders seem to be all issued for character

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#77]
I recently added a buy order for my corporation but it shows up as Issued For **'Character'**. 

My Balance also shows up yellow/orange and i get a character notification that my funds are not enough for the buy order. It seems ESI data is not parsed correctly.

Finally partial fulfillment of this corporation buy order is shows as a corporate wallet transaction (which is correct).

**Comment by peterhaneve** [comment]
Does this issue only affect buy orders, or are sell orders also affected?

**Comment by peterhaneve** [comment]
Are _corporation_ orders made on behalf of a character being returned in a query for _character_ market orders? There is a whole separate endpoint listed for corporation market orders, and I had been using that one and classifying all of those as the corporation orders.

**Comment by wvdvegt** [comment]
The endpoint i see with Fiddler is 

https://esi.evetech.net/v2/characters/<id>/orders/

This JSON contains the is_corporation boolean field to signal it's charged against corp wallets which i mentioned earlier. I assume this endpoint makes it possible to tag orders as corporate without access to the corporate order endpoint.

I have no clue how i can make a corp only order (they always seem to be tied to the issuer as he/she is the one that can modify the order).

**Comment by wvdvegt** [comment]
I did some tracing and it seems like it's caused by the line:

`target.CharacterMarketOrders.Import(result, IssuedFor.Character, endedOrders);`

in `CharacterDataQuerying.OnMarketOrdersUpdated(EsiAPIMarketOrders result) `

and a similar line for Corporate Import (both have a hardcoded IssueFor instead of getting the info from the order itself.

Here the market orders are imported and all marked as issued for character based on the endpoint i assume. But the character endpoint also contains corporate items marked by 'is_corporation' as mentioned in an earlier comment.

I think the result is that the first call wins (either corporate or character querying) as the code seem to take care of duplicates.

I will try to make a new pull request but here already the fixes 

In `MarketOrder.cs / MarketOrder(EsiOrderListItem src, IssuedFor issuedFor, CCPCharacter character)`

Change the issuedFor line into:

```
// veg Fix 1
issuedFor = src.IsCorporation || src.IssuedBy == 0  ? IssuedFor.Corporation : IssuedFor.Character;
```
In `MarketOrder.cs / private void PopulateOrderInfo(EsiOrderListItem src, IssuedFor issuedFor)
`
Change the issuedFor line into:

```
// veg Fix 2
issuedFor = src.IsCorporation || src.IssuedBy == 0  ? IssuedFor.Corporation : IssuedFor.Character;
```
I think it's safe to remove the IssuedFor parameters in both methods.

This patch also needs the lines:

```
// veg Fix 3

/// <summary>
/// True if this is a corporation order, false otherwise.
 /// </summary>
[DataMember(Name = "is_corporation")]
public bool IsCorporation { get; set; }
```
to be added to EsiOrderListItem.cs

What happens is indeed an order issue, corporate orders do not contain the 'is_corporation' flag/value but use IssuedBy = 0 instead. Character orders on the other hand contain the 'is_corporation' flag and have a valid characterID in IssuedBy (the pilot who placed the order, not usable for determining if the order is corporate). I further expect the corporate endpoint to return all corporate orders so also from other pilots (but am not able to check this).
