### ISSUE TITLE
Planetary Production doesn't say the system they are in

### ISSUE THREAD

**Issue by mikeyhalla** [peterhaneve/evemon#84]
Planetary Production doesn't say the system they are in which would be nice to know. I am in a situation where that would be a nice feature.

**Comment by peterhaneve** [comment]
The PI system is available, but hidden by default. You may need to change the column settings.

**Comment by mikeyhalla** [comment]
Sorry, I overlooked it. Evemon is huge like eve is and i'm still learning both. Thank you very much for pointing this out.
