### ISSUE TITLE
About page contains old URL

### ISSUE THREAD

**Issue by kwazulueve** [peterhaneve/evemon#85]
In the About page there is the link https://evemondevteam.github.io/evemon/ which is outdated, perhaps replace with your own? Thanks for your great work

**Comment by peterhaneve** [comment]
This old page contains lots of good information which has changed little since it was written, and duplicating it would be very time consuming. Aside from setting up characters (which is covered by https://peterhaneve.github.io/evemon-esi), most of that information is still valid.
