### ISSUE TITLE
Move to PKCE (instead of client secret)

### ISSUE THREAD

**Issue by GoldenGnu** [peterhaneve/evemon#91]
I just wanted to suggest you move EveMon to PKCE (as documented here: https://github.com/esi/esi-docs/blob/master/docs/sso/native_sso_flow.md)
It will allow EveMon to work without a client secret and thereby allow people with only alphas to use EveMon too.

**Comment by wvdvegt** [comment]
This link might help (shows how to obtain a code verifier with C#):

https://medium.com/@costeijnk/auth0-pkce-flow-in-c-cafe111dce7f

**Comment by wvdvegt** [comment]
Some remarks (just got my own code working, online docs are not complete): 

- The new oath api supporting PCKE starts with 'v2' (so '/v2/oauth/token').
- The Host header with value 'login.eveonline.com' is mandatory when refreshing a access token you need to add the client_id to the stuff encoded in the body like 
`String body = $"grant_type=refresh_token&client_id=<ClientID>&refresh_token=<Refresh_token>";`
- The existing Authorization header needs to be removed (so no more secrets).
- The "Content-Type" header now has a value of "application/x-www-form-urlencoded".
