### ISSUE TITLE
Implants Calculator

### ISSUE THREAD

**Issue by ZombieErebus** [peterhaneve/evemon#92]
Hi, Firstly a big thank you for the work you are doing to keep this tool working. Secondly, I've noticed that with the new Evemon when looking at a skill plan, if you click the "implants Calculator" button you can only take the number down from its current value which isn't entirely helpful when trying to work out whether or not to buy certain implants. I hope this makes sense

**Comment by peterhaneve** [comment]
The implant calculator, although possibly poorly named, is intended for optimizing attributes. You can add a custom clone set with all +5s and select it from the clone list drop down if you are trying to find out the gain from implants.
