### ISSUE TITLE
Summary combox stays visible after editing

### ISSUE THREAD

**Issue by wvdvegt** [peterhaneve/evemon#93]
I replaced the CharacterMonitorHeader.cs / CustomLabelComboBox_KeyUp

with 

```
        private void CustomLabelComboBox_KeyUp(object sender, KeyEventArgs e)
        {
            if ((e.KeyCode == Keys.Enter || e.KeyCode == Keys.Return) && !m_updatingLabels)
            {
                m_character.Label = CustomLabelComboBox.Text;

                CustomLabelComboBox.Visible = false;
                CustomLabelLink.Visible = true;

                e.Handled = true;
            }
        }

```

So after editing with the combox, the (CustomLabelLink) label is shown again preventing stealing focus.

**Comment by peterhaneve** [comment]
How is this stealing focus? The user had to select it in the first place. The intent is to leave the combo box present after editing since users will change it a minority of the time.

**Comment by wvdvegt** [comment]
This fix turns the. combobox back into the edit label when your done editing (press return). As such it prevents accidental editing as you have click it to edit once more.

**Comment by wvdvegt** [comment]
This is what the fix looks like (a label that can be clicked if you edited it):

![annotation](https://user-images.githubusercontent.com/1768983/46672769-93eda680-cbd8-11e8-9a7f-d4b3cd4ff225.png)

IMHO the feature will set not that often but used to mark cyno alts etc. Most other useful info like whereabouts is already available in EveMon.
